import { randomBytes, randomUUID, scrypt as scryptCallback, timingSafeEqual } from "node:crypto";
import { readFile } from "node:fs/promises";
import { promisify } from "node:util";
import { ABILITIES, CATEGORIES, CHARACTERS, NAMES, TAGS } from "./content.js";
import type { Account,Auction,AuthToken,Category,ClientMessage,Deployment,GameSnapshot,HouseState,HouseSummary,Item,MarketHistory,MarketSale,MarketSummary,MemberOrder,Order,Player,PrivateState,PublicHouseDetail,PublicItem,PublicState,Season,ServerConfig } from "../shared/types.js";

const scrypt=promisify(scryptCallback),fakeRates=[0,.1,.25,.5,.7],tierBaseValues=[0,40,120,400,1500],TOKEN_MS=30*86400000,WARNING_MS=300000,DAY_MS=86400000;
const LEVEL_CAP=20,LEVEL_XP_FACTOR=100,COOLDOWN_MIN=.6,COOLDOWN_STEP=.02,PULL_COST=150,LIST_MIN=2,LIST_MAX=3600;
const pick=<T>(xs:readonly T[]):T=>xs[Math.floor(Math.random()*xs.length)]!;
const abilityIds=(characterId:string):string[]=>{const c=CHARACTERS.find(x=>x.id===characterId);if(!c)throw new GameError("Unknown character");return [c.mainAbility,...c.traits];};
const publicItem=(i:Item):PublicItem=>({id:i.id,name:i.name,category:i.category,tier:i.tier,tags:[...i.tags],art:`items/art-${i.category.toLowerCase()}-${i.tier}.png`});
const legacyMessage="Action is unavailable in this house";
export class GameError extends Error {}
export interface SettlementNotice { message:string; houseId:string; participantIds:string[]; paid:boolean }
type Options={houseCap?:number;maxDeploys?:number;featuredIntervalMinutes?:number;joinStipendAfterHours?:number;joinStipendMax?:number;rookieWindowHours?:number;slipClaimMax?:number;slipPriceCeiling?:number;boxPrice?:number;movePenaltyMs?:number};

export class GameState {
 readonly accounts=new Map<string,Account>();readonly tokens=new Map<string,AuthToken>();readonly players=new Map<string,Player>();readonly items=new Map<string,Item>();readonly houses=new Map<string,HouseState>();readonly peeks=new Map<string,Map<string,boolean>>();readonly marketLedger:MarketSale[]=[];readonly settledAuctionIds=new Set<string>();
 season:Season;private readonly seasonMs:number;readonly houseCap:number;readonly maxDeploys:number;readonly featuredIntervalMs:number;readonly joinStipendAfterHours:number;readonly joinStipendMax:number;readonly rookieWindowHours:number;readonly slipClaimMax:number;readonly slipPriceCeiling:number;readonly boxPrice:number;readonly movePenaltyMs:number;
 constructor(private readonly onMutation:()=>void=()=>{},seasonHours=672,snapshot?:GameSnapshot,opts:Options={}){
  this.seasonMs=Math.max(1/3600,seasonHours)*3600000;this.houseCap=Math.max(1,opts.houseCap??Number(process.env.HOUSE_CAP??8));this.maxDeploys=Math.max(1,opts.maxDeploys??Number(process.env.MAX_DEPLOYS??3));this.featuredIntervalMs=Math.max(.001,opts.featuredIntervalMinutes??Number(process.env.FEATURED_INTERVAL_MINUTES??30))*60000;
  this.joinStipendAfterHours=Math.max(0,opts.joinStipendAfterHours??Number(process.env.JOIN_STIPEND_AFTER_HOURS??24));this.joinStipendMax=Math.max(500,opts.joinStipendMax??Number(process.env.JOIN_STIPEND_MAX??2000));this.rookieWindowHours=Math.max(0,opts.rookieWindowHours??Number(process.env.ROOKIE_WINDOW_HOURS??336));this.slipClaimMax=Math.max(0,Math.floor(opts.slipClaimMax??Number(process.env.SLIP_CLAIM_MAX??10)));this.slipPriceCeiling=Math.max(0,opts.slipPriceCeiling??Number(process.env.SLIP_PRICE_CEILING??.15));this.boxPrice=Math.max(0,opts.boxPrice??Number(process.env.BOX_PRICE??100));this.movePenaltyMs=Math.max(0,opts.movePenaltyMs??Number(process.env.MOVE_PENALTY_MS??DAY_MS));
  const now=Date.now();this.season={number:1,startedAt:now,endsAt:now+this.seasonMs,phase:"active"};if(snapshot)this.restore(snapshot);else this.createHouse(true);
 }
 static async load(path:string,onMutation:()=>void=()=>{},seasonHours=672,opts:Options={}):Promise<GameState>{
  const raw=JSON.parse(await readFile(path,"utf8")) as Record<string,unknown>;const version=raw.schemaVersion;
  if(version===3)return new GameState(onMutation,seasonHours,raw as unknown as GameSnapshot,opts);
  if(version!==1&&version!==2)throw new Error(`Unsupported state schema: ${String(version)}`);
  const legacy=raw as unknown as {accounts:Account[];tokens:AuthToken[];players:Array<Omit<Player,"roster"|"bidderXp"|"movePenaltyUntil">>;items:Item[];houses?:HouseState[];auctions?:Auction[];orders?:Order[];peeks:Array<[string,Array<[string,boolean]>]>;season:Season};
  const g=new GameState(onMutation,seasonHours,undefined,opts);g.accounts.clear();g.houses.clear();
  if(version===1){const h=g.blankHouse("house-1","Grand Exchange",null,.05,20);h.auctions=(legacy.auctions??[]).map(a=>({...a,listingFeePaid:a.listingFeePaid??0}));h.orders=legacy.orders??[];g.houses.set(h.id,h);}else for(const h of legacy.houses??[])g.houses.set(h.id,h);
  legacy.accounts.forEach(x=>g.accounts.set(x.id,x));legacy.tokens.filter(x=>x.expiresAt>Date.now()).forEach(x=>g.tokens.set(x.token,x));
  legacy.players.forEach(x=>{const deployments=[...g.houses.values()].flatMap(h=>h.deployments.filter(d=>d.playerId===x.id)),deployed=deployments.map(d=>d.characterId),bidderXp=Object.fromEntries(deployments.map(d=>[d.characterId,d.xp]));const roster=[...new Set([x.characterId,...deployed].filter(Boolean))];g.players.set(x.id,g.normalizePlayer({...x,roster,bidderXp,movePenaltyUntil:{}} as Player));});
  if(version===1)for(const p of g.players.values())g.houses.get("house-1")!.deployments.push({playerId:p.id,characterId:p.characterId,xp:p.xp,redeployCooldownUntil:0});
  legacy.items.forEach(x=>g.items.set(x.id,x));legacy.peeks.forEach(([id,e])=>g.peeks.set(id,new Map(e)));g.season=legacy.season;for(const h of g.houses.values()){h.nextFeaturedAt ||= g.nextFeatured(h.primeHour);g.fillOrders(h);}return g;
 }
 private normalizePlayer(p:Player):Player{return {...p,roster:[...new Set([...(Array.isArray(p.roster)?p.roster:[]),p.characterId].filter(Boolean))],bidderXp:p.bidderXp??{},movePenaltyUntil:p.movePenaltyUntil??{},stipendAwardedThisSeason:p.stipendAwardedThisSeason??true,rookie:p.rookie??false,slipClaims:Array.isArray(p.slipClaims)?p.slipClaims:[]};}
 private restore(s:GameSnapshot){s.accounts.forEach(x=>this.accounts.set(x.id,x));s.tokens.filter(x=>x.expiresAt>Date.now()).forEach(x=>this.tokens.set(x.token,x));s.players.forEach(x=>this.players.set(x.id,this.normalizePlayer(x)));s.items.forEach(x=>this.items.set(x.id,x));s.houses.forEach(x=>this.houses.set(x.id,x));s.peeks.forEach(([id,e])=>this.peeks.set(id,new Map(e)));this.season=s.season;for(const sale of s.marketLedger??[])this.marketLedger.push(sale);for(const id of s.settledAuctionIds??[])this.settledAuctionIds.add(id);if(!this.houses.size)this.createHouse(true);for(const h of this.houses.values()){h.nextFeaturedAt ||= this.nextFeatured(h.primeHour);this.fillOrders(h);}}
 snapshot():GameSnapshot{return {schemaVersion:3,accounts:[...this.accounts.values()],tokens:[...this.tokens.values()],players:[...this.players.values()],items:[...this.items.values()],houses:[...this.houses.values()],peeks:[...this.peeks].map(([id,p])=>[id,[...p]]),season:this.season,marketLedger:[...this.marketLedger],settledAuctionIds:[...this.settledAuctionIds]};}
 config():ServerConfig{return {boxPrice:this.boxPrice,listingDurationMinSec:LIST_MIN,listingDurationMaxSec:LIST_MAX,houseCap:this.houseCap,maxDeploys:this.maxDeploys,movePenaltyMs:this.movePenaltyMs,bidderPullCost:PULL_COST,levelCap:LEVEL_CAP,levelXpFactor:LEVEL_XP_FACTOR,cooldownMinMultiplier:COOLDOWN_MIN,cooldownReductionPerLevel:COOLDOWN_STEP};}
 private changed(){this.onMutation();}
 static levelForXp(xp:number){let level=1,remaining=Math.max(0,xp);while(level<LEVEL_CAP&&remaining>=LEVEL_XP_FACTOR*level){remaining-=LEVEL_XP_FACTOR*level;level++;}return level;}
 static cooldownMultiplier(xp:number){return Math.max(COOLDOWN_MIN,1-COOLDOWN_STEP*(GameState.levelForXp(xp)-1));}
 private deploymentView(d:Deployment,houseId:string,now=Date.now()){const level=GameState.levelForXp(d.xp);return {...d,houseId,level,xpPaused:d.redeployCooldownUntil>now,cooldownMultiplier:GameState.cooldownMultiplier(d.xp)};}
 private nextFeatured(hour:number,now=Date.now()){const d=new Date(now),anchor=Date.UTC(d.getUTCFullYear(),d.getUTCMonth(),d.getUTCDate(),hour),n=anchor+Math.ceil((now-anchor)/this.featuredIntervalMs)*this.featuredIntervalMs;return n<=now?n+this.featuredIntervalMs:n;}
 private blankHouse(id:string,name:string,specialtyTag:string|null,feeRate:number,primeHour:number):HouseState{return {id,name,specialtyTag,feeRate,primeHour,auctions:[],orders:[],deployments:[],nextFeaturedAt:this.nextFeatured(primeHour)};}
 private createHouse(first=false){const adjs=["Velvet","Golden","Silver","Moonlit","Royal","Hidden","Crimson","Ivory"],nouns=["Harbor","Exchange","Gallery","Bazaar","Arcade","Salon","Market","Atrium"];let name=first?"Grand Exchange":`${pick(adjs)} ${pick(nouns)}`;while([...this.houses.values()].some(h=>h.name===name))name=`${pick(adjs)} ${pick(nouns)}`;const h=this.blankHouse(first?"house-1":`house-${this.houses.size+1}`,name,first?null:(Math.random()<.85?pick(TAGS):null),first?.05:Number((.03+Math.random()*.09).toFixed(2)),first?20:Math.floor(Math.random()*24));this.houses.set(h.id,h);this.fillOrders(h);this.changed();return h;}
 private addOrder(h:HouseState,forceSpecialty=false){const tierMin=Math.random()<.75?1:2,fakeAllowed=Math.random()<.65,special=!!h.specialtyTag&&(forceSpecialty||Math.random()<.5);const template=special?{tag:h.specialtyTag!,tierMin,count:1,fakeAllowed}:Math.random()<.5?{category:pick(CATEGORIES),tierMin,count:1,fakeAllowed}:{tag:pick(TAGS),tierMin,count:1,fakeAllowed};const mult=tierMin+(fakeAllowed?0:1);h.orders.push({id:randomUUID(),template,reward:{coins:80*mult,fame:100*mult,xp:50*mult}});}
 private fillOrders(h:HouseState){while(h.orders.length<6)this.addOrder(h,!!h.specialtyTag&&h.orders.filter(o=>o.template.tag===h.specialtyTag).length<3);}
 async register(username:string,password:string){const clean=validateCredentials(username,password),key=clean.toLowerCase();if([...this.accounts.values()].some(a=>a.usernameKey===key))throw new GameError("Username is already registered");const salt=randomBytes(16).toString("hex"),passwordHash=await hash(password,salt),id=randomUUID();this.accounts.set(id,{id,username:clean,usernameKey:key,passwordHash,salt});const token=this.issue(id);this.changed();return {token,playerId:id};}
 async login(username:string,password:string){const a=[...this.accounts.values()].find(x=>x.usernameKey===username.trim().toLowerCase());if(!a)throw new GameError("Invalid username or password");const c=Buffer.from(await hash(password,a.salt),"hex"),s=Buffer.from(a.passwordHash,"hex");if(c.length!==s.length||!timingSafeEqual(c,s))throw new GameError("Invalid username or password");const token=this.issue(a.id);this.changed();return {token,playerId:a.id};}
 private issue(playerId:string){const token=randomBytes(32).toString("hex");this.tokens.set(token,{token,playerId,expiresAt:Date.now()+TOKEN_MS});return token;}
 authenticate(token:string){const t=this.tokens.get(token);if(!t||t.expiresAt<=Date.now())throw new GameError("Invalid or expired token");t.expiresAt=Date.now()+TOKEN_MS;const account=this.accounts.get(t.playerId);if(!account)throw new GameError("Account not found");this.changed();const player=this.players.get(account.id);return player?{account,player}:{account};}
 private ensurePlayer(pid:string,characterId:string){const old=this.players.get(pid);if(old)return old;const a=this.accounts.get(pid);if(!a)throw new GameError("Authenticate first");abilityIds(characterId);a.characterId=characterId;const p:Player={id:pid,name:a.username,characterId,roster:[characterId],bidderXp:{[characterId]:0},movePenaltyUntil:{},coins:0,inventory:[],xp:0,fame:0,abilities:{},boxes:2,fameMilestones:[],stipendAwardedThisSeason:false,rookie:false,slipClaims:[]};this.players.set(pid,p);this.peeks.set(pid,new Map());return p;}
 join(pid:string,now=Date.now()){const p=this.players.get(pid);if(!p||!this.deployments(pid).length)throw new GameError("Deploy a character to a house first");let stipendAwarded:number|undefined;if(!p.stipendAwardedThisSeason){const hoursLate=Math.max(0,(now-this.season.startedAt)/3600000);stipendAwarded=hoursLate>=this.joinStipendAfterHours?Math.min(this.joinStipendMax,500+250*Math.floor(hoursLate/24)):500;p.coins+=stipendAwarded;p.stipendAwardedThisSeason=true;p.rookie=this.season.endsAt-now<this.rookieWindowHours*3600000;this.changed();}return {player:p,...(stipendAwarded!==undefined?{stipendAwarded}:{})};}
 deployments(pid:string){return [...this.houses.values()].flatMap(h=>h.deployments.filter(d=>d.playerId===pid).map(d=>this.deploymentView(d,h.id)));}
 deploy(pid:string,houseId:string,characterId:string){const h=this.house(houseId),all=this.deployments(pid);abilityIds(characterId);const p=this.players.get(pid)??this.ensurePlayer(pid,characterId);if(!p.roster.includes(characterId))throw new GameError("You do not own this bidder");if((p.movePenaltyUntil[characterId]??0)>Date.now())throw new GameError("This bidder cannot be deployed until the move penalty expires");if(h.deployments.some(d=>d.playerId===pid))throw new GameError("You already have a character deployed to this house");if(all.length>=this.maxDeploys)throw new GameError(`Maximum ${this.maxDeploys} deployments reached`);if(all.some(d=>d.characterId===characterId))throw new GameError("Character is already deployed");for(const id of abilityIds(characterId))p.abilities[id]??={readyAt:0,uses:0};const d:Deployment={playerId:pid,characterId,xp:p.bidderXp[characterId]??0,redeployCooldownUntil:0};h.deployments.push(d);this.changed();return d;}
 pullBidder(pid:string){const p=this.player(pid),available=CHARACTERS.filter(c=>!p.roster.includes(c.id));if(!available.length)throw new GameError("All bidders are already owned");if(p.coins<PULL_COST)throw new GameError(`Not enough coins; bidder pulls cost ${PULL_COST}`);p.coins-=PULL_COST;const c=pick(available);p.roster.push(c.id);this.changed();return c;}
 redeploy(pid:string,characterId:string,toHouseId:string,now=Date.now()){const p=this.player(pid);if((p.movePenaltyUntil[characterId]??0)>now)throw new GameError("This bidder cannot move again until the move penalty expires");const target=this.house(toHouseId);let source:HouseState|undefined,dep:Deployment|undefined;for(const h of this.houses.values()){dep=h.deployments.find(d=>d.playerId===pid&&d.characterId===characterId);if(dep){source=h;break;}}if(!source||!dep)throw new GameError("Character is not deployed");if(source.id===target.id)throw new GameError("Character is already deployed to that house");const until=now+this.movePenaltyMs;p.movePenaltyUntil[characterId]=until;source.deployments=source.deployments.filter(d=>d!==dep);dep.redeployCooldownUntil=until;target.deployments.push(dep);this.changed();return dep;}
 recall(pid:string,characterId:string,now=Date.now()){const p=this.player(pid);if((p.movePenaltyUntil[characterId]??0)>now)throw new GameError("This bidder cannot move again until the move penalty expires");for(const h of this.houses.values()){const dep=h.deployments.find(d=>d.playerId===pid&&d.characterId===characterId);if(dep){p.bidderXp[characterId]=dep.xp;p.movePenaltyUntil[characterId]=now+this.movePenaltyMs;h.deployments=h.deployments.filter(d=>d!==dep);this.changed();return {houseId:h.id,characterId};}}throw new GameError("Character is not deployed");}
 private house(id:string){const h=this.houses.get(id);if(!h)throw new GameError("Unknown house");return h;}
 requireDeployment(pid:string,houseId:string){const house=this.houses.get(houseId),deployment=house?.deployments.find(d=>d.playerId===pid);if(!house||!deployment)throw new GameError(legacyMessage);return {house,deployment};}
 private player(pid:string){const p=this.players.get(pid);if(!p)throw new GameError("Deploy a character first");return p;}
 private makeItem(owner:string):Item{const r=Math.random(),tier:1|2|3|4=r<.55?1:r<.82?2:r<.96?3:4,category=pick(CATEGORIES),tags=[...TAGS].sort(()=>Math.random()-.5).slice(0,Math.random()<.5?2:3);return {id:randomUUID(),name:`${["Plain","Fine","Exquisite","Legendary"][tier-1]} ${NAMES[category][tier-1]}`,category,tier,tags,fake:Math.random()<fakeRates[tier]!,history:[{owner,price:0,ts:Date.now()}]};}
 openBox(pid:string){const p=this.player(pid);if(p.boxes>0)p.boxes--;else if(p.coins>=this.boxPrice)p.coins-=this.boxPrice;else throw new GameError("Not enough coins");const i=this.makeItem(p.name);this.items.set(i.id,i);p.inventory.push(i.id);this.changed();return i;}
 list(pid:string,houseId:string,itemId:string,durationSec:number){const {house}=this.requireDeployment(pid,houseId),p=this.player(pid);if(!p.inventory.includes(itemId))throw new GameError("Item is not in your inventory");if(!Number.isFinite(durationSec))throw new GameError("Invalid duration");const duration=Math.max(LIST_MIN,Math.min(LIST_MAX,durationSec)),fee=Math.ceil(duration*house.feeRate);if(p.coins<fee)throw new GameError("Not enough coins for listing fee");p.coins-=fee;p.inventory=p.inventory.filter(x=>x!==itemId);const auction:Auction={id:randomUUID(),itemId,sellerId:pid,bids:[],endsAt:Date.now()+duration*1000,featured:false,listingFeePaid:fee,blocked:[]};house.auctions.push(auction);const spawned=new Set(house.deployments.map(d=>d.playerId)).size>=this.houseCap&&![...this.houses.values()].some(h=>h.id!==house.id&&new Set(h.deployments.map(d=>d.playerId)).size<this.houseCap)?this.createHouse():undefined;this.changed();return {auction,spawned};}
 private slipCeiling(item:Item){return tierBaseValues[item.tier]!*this.slipPriceCeiling;}private recentSlipClaims(p:Player,now=Date.now()){p.slipClaims=p.slipClaims.filter(ts=>ts>now-DAY_MS);return p.slipClaims;}private pendingSlipClaims(pid:string,excludeAuctionId:string){let count=0;for(const h of this.houses.values())for(const a of h.auctions){if(a.id===excludeAuctionId||a.endsAt<=Date.now())continue;const top=a.bids.at(-1),item=this.items.get(a.itemId);if(top?.playerId===pid&&item&&top.amount<=this.slipCeiling(item))count++;}return count;}
 bid(pid:string,houseId:string,auctionId:string,amount:number){const {house}=this.requireDeployment(pid,houseId),p=this.player(pid),a=house.auctions.find(x=>x.id===auctionId);if(!a||a.endsAt<=Date.now())throw new GameError(legacyMessage);if(a.blocked?.includes(pid))throw new GameError("You are blocked from this auction");const top=a.bids.at(-1);if(a.shield&&a.shield.until>Date.now()&&a.shield.playerId!==pid)throw new GameError("Leading bid is shielded");const min=top?Math.max(top.amount+10,Math.ceil(top.amount*1.05)):10;if(!Number.isInteger(amount)||amount<min)throw new GameError(`Minimum bid is ${min}`);if(p.coins<amount)throw new GameError("Not enough coins");const item=this.items.get(a.itemId);if(item&&amount<=this.slipCeiling(item)&&this.recentSlipClaims(p).length+this.pendingSlipClaims(pid,a.id)>=this.slipClaimMax)throw new GameError("Slip-claim limit reached ??try higher-value auctions.");a.bids.push({playerId:pid,amount,ts:Date.now()});if(a.endsAt-Date.now()<=5000)a.endsAt=Date.now()+5000;this.changed();}
 fulfill(pid:string,houseId:string,orderId:string,itemIds:string[]){const {house,deployment}=this.requireDeployment(pid,houseId),p=this.player(pid),o=house.orders.find(x=>x.id===orderId);if(!o)throw new GameError(legacyMessage);if(itemIds.length!==o.template.count||new Set(itemIds).size!==itemIds.length)throw new GameError("Wrong item count");const chosen=itemIds.map(id=>{if(!p.inventory.includes(id))throw new GameError("Item is not in your inventory");const item=this.items.get(id);if(!item)throw new GameError("Item is not in your inventory");return item;});if(!chosen.every(i=>(!o.template.category||i.category===o.template.category)&&(!o.template.tag||i.tags.includes(o.template.tag))&&i.tier>=o.template.tierMin&&(o.template.fakeAllowed||!i.fake)))throw new GameError("Items do not match order");for(const i of chosen){p.inventory=p.inventory.filter(id=>id!==i.id);this.items.delete(i.id);}p.coins+=o.reward.coins;p.fame+=o.reward.fame;if(deployment.redeployCooldownUntil<=Date.now()){deployment.xp+=o.reward.xp;p.bidderXp[deployment.characterId]=deployment.xp;}this.milestones(p);house.orders=house.orders.filter(x=>x.id!==orderId);this.fillOrders(house);this.changed();}
 useAbility(pid:string,houseId:string,msg:Extract<ClientMessage,{type:"USE_ABILITY"}>){const {house,deployment}=this.requireDeployment(pid,houseId);if(deployment.redeployCooldownUntil>Date.now())throw new GameError("Character abilities are unavailable during move cooldown");const p=this.player(pid),def=ABILITIES.find(a=>a.id===msg.abilityId);if(!def||!abilityIds(deployment.characterId).includes(def.id))throw new GameError("Ability is not equipped");const cd=p.abilities[def.id]??(p.abilities[def.id]={readyAt:0,uses:0});if(cd.readyAt>Date.now())throw new GameError("Ability is cooling down");if(def.maxUses!==undefined&&cd.uses>=def.maxUses)throw new GameError("No uses remaining");const a=msg.auctionId?house.auctions.find(x=>x.id===msg.auctionId):undefined;if(["peek","reveal","shield","refund","tax","block"].includes(def.kind)&&!a)throw new GameError(legacyMessage);if(def.kind==="peek"||def.kind==="reveal")this.peeks.get(pid)!.set(a!.itemId,this.items.get(a!.itemId)!.fake);else if(def.kind==="shield"){const top=a!.bids.at(-1);if(!top||top.playerId!==pid)throw new GameError("You must lead this auction");a!.shield={playerId:pid,until:Date.now()+10000};}else if(def.kind==="refund"){const top=a!.bids.at(-1);if(!top||top.playerId!==pid)throw new GameError("You have no leading bid to refund");a!.bids.pop();}else if(def.kind==="tax")a!.taxRate=.1;else if(def.kind==="block"){if(!msg.targetPlayerId||msg.targetPlayerId===pid||msg.targetPlayerId===a!.sellerId)throw new GameError("Choose another bidder");a!.blocked=[...(a!.blocked??[]),msg.targetPlayerId];}else if(def.kind==="coin")p.coins+=20;else for(const s of Object.values(p.abilities))s.readyAt=Math.max(Date.now(),s.readyAt-30000);cd.readyAt=Date.now()+Math.round(def.cooldownMs*GameState.cooldownMultiplier(deployment.xp));cd.uses++;this.changed();return `${def.name} used`;}
 settle(cutoff=Date.now(),settledAt=cutoff){const notices:SettlementNotice[]=[];for(const h of this.houses.values())for(const a of [...h.auctions])if(a.endsAt<=cutoff){const seller=this.player(a.sellerId),item=this.items.get(a.itemId),top=a.bids.at(-1);if(item){if(top){const buyer=this.player(top.playerId),extra=Math.ceil(top.amount*(a.taxRate??0));if(buyer.coins>=top.amount+extra){buyer.coins-=top.amount+extra;seller.coins+=Math.floor(top.amount*(1-h.feeRate));buyer.inventory.push(item.id);item.history.push({owner:buyer.name,price:top.amount,ts:settledAt});if(!this.settledAuctionIds.has(a.id)){this.marketLedger.push({saleId:a.id,templateKey:`${item.category}:${item.tier}`,price:top.amount,tags:[...item.tags],settledAt,season:this.season.number});this.settledAuctionIds.add(a.id);}if(top.amount<=this.slipCeiling(item)){const count=this.recentSlipClaims(buyer,settledAt).push(settledAt);console.log(`[slip] player=${buyer.id} auction=${a.id} price=${top.amount} count=${count}`);}if(a.featured){const reward=Math.ceil(top.amount*.25);buyer.fame+=reward;const dep=h.deployments.find(d=>d.playerId===buyer.id);if(dep&&dep.redeployCooldownUntil<=settledAt){dep.xp+=reward;buyer.bidderXp[dep.characterId]=dep.xp;}this.milestones(buyer);}notices.push({message:`${item.name} sold for ${top.amount}`,houseId:h.id,participantIds:[seller.id,buyer.id],paid:true});}else{seller.inventory.push(item.id);notices.push({message:`${item.name} returned unsold`,houseId:h.id,participantIds:[seller.id],paid:false});}}else seller.inventory.push(item.id);}h.auctions=h.auctions.filter(x=>x.id!==a.id);}if(notices.length)this.changed();return notices;}
 private milestones(p:Player){for(const m of [500,1500,4000])if(p.fame>=m&&!p.fameMilestones.includes(m)){p.fameMilestones.push(m);p.coins+=m===500?100:m===1500?300:800;}}
 promoteHouse(houseId:string,now=Date.now()){const h=this.house(houseId);for(const a of h.auctions)a.featured=false;const best=h.auctions.filter(a=>a.endsAt>now).sort((a,b)=>this.items.get(b.itemId)!.tier-this.items.get(a.itemId)!.tier||b.listingFeePaid-a.listingFeePaid||a.endsAt-b.endsAt)[0];if(best){best.featured=true;this.changed();}return best;}
 tickFeatured(now=Date.now()){const out:Array<{houseId:string;auctionId:string}>=[];for(const h of this.houses.values())if(now>=h.nextFeaturedAt){const a=this.promoteHouse(h.id,now);h.nextFeaturedAt=this.nextFeatured(h.primeHour,now);if(a)out.push({houseId:h.id,auctionId:a.id});this.changed();}return out;}
 tickSeason(now=Date.now()){let warning=false;if(this.season.phase==="active"&&now>=this.season.endsAt-WARNING_MS){this.season.phase="ending";warning=true;this.changed();}if(now<this.season.endsAt)return {warning,settlements:[]};return {warning,ended:this.season.number+1,settlements:this.endSeason(now)};}forceEndSeason(now=Date.now()){return {number:this.season.number+1,settlements:this.endSeason(now)};}
 private endSeason(now:number){const settlements=this.settle(Infinity,now);this.items.clear();this.peeks.clear();this.marketLedger.length=0;this.settledAuctionIds.clear();for(const h of this.houses.values()){h.auctions=[];h.orders=[];for(const d of h.deployments){d.redeployCooldownUntil=0;d.xp=0;}this.fillOrders(h);h.nextFeaturedAt=this.nextFeatured(h.primeHour,now);}for(const p of this.players.values()){p.coins=500;p.xp=0;p.fame=0;p.inventory=[];p.boxes=2;p.fameMilestones=[];p.abilities={};p.bidderXp={};p.movePenaltyUntil={};p.stipendAwardedThisSeason=true;p.rookie=false;p.slipClaims=[];for(const d of this.deployments(p.id))for(const id of abilityIds(d.characterId))p.abilities[id]={readyAt:0,uses:0};this.peeks.set(p.id,new Map());}this.season={number:this.season.number+1,startedAt:now,endsAt:now+this.seasonMs,phase:"active"};this.changed();return settlements;}
 privateState(pid:string,currentHouseId?:string,stipendAwarded?:number):PrivateState{return {player:this.player(pid),items:this.player(pid).inventory.map(id=>this.items.get(id)!).filter((x):x is Item=>!!x),peeked:Object.fromEntries(this.peeks.get(pid)??[]),deployments:this.deployments(pid),...(currentHouseId&&this.deployments(pid).some(d=>d.houseId===currentHouseId)?{currentHouseId}:{}),...(stipendAwarded!==undefined?{stipendAwarded}:{})};}
 memberOrders(pid:string):MemberOrder[]{return [...this.houses.values()].flatMap(h=>h.deployments.filter(d=>d.playerId===pid).flatMap(d=>h.orders.map(order=>({houseId:h.id,characterId:d.characterId,xpPaused:d.redeployCooldownUntil>Date.now(),order}))));}
 marketSummary(now=Date.now()):MarketSummary{const templates=[];for(const category of CATEGORIES)for(const tier of [1,2,3,4] as const){const key=`${category}:${tier}`,rows=this.marketLedger.filter(x=>x.templateKey===key),last=[...rows].sort((a,b)=>b.settledAt-a.settledAt||b.saleId.localeCompare(a.saleId))[0];templates.push({templateKey:key,name:`${["Plain","Fine","Exquisite","Legendary"][tier-1]} ${NAMES[category][tier-1]}`,category,tier,count:rows.length,averagePrice:rows.length?rows.reduce((n,x)=>n+x.price,0)/rows.length:null,lastPrice:last?.price??null,lastSettledAt:last?.settledAt??null});}return {coverage:"current-season",season:this.season.number,templates,asOf:now};}
 marketHistory(templateKey:string,cursor?:string,limit=50,now=Date.now()):MarketHistory{if(!CATEGORIES.some(c=>[1,2,3,4].some(t=>`${c}:${t}`===templateKey)))throw new GameError("Unknown market template");const size=Math.max(1,Math.min(100,Number.isInteger(limit)?limit:50)),all=this.marketLedger.filter(x=>x.templateKey===templateKey).sort((a,b)=>b.settledAt-a.settledAt||b.saleId.localeCompare(a.saleId));let start=0;if(cursor){const index=all.findIndex(x=>x.saleId===cursor);if(index<0)throw new GameError("Invalid market cursor");start=index+1;}const rows=all.slice(start,start+size),next=start+size<all.length?rows.at(-1)?.saleId:undefined;return {coverage:"current-season",season:this.season.number,templateKey,rows,...(next?{nextCursor:next}:{}),asOf:now};}
 houseSummaries():HouseSummary[]{return [...this.houses.values()].map(h=>{const memberCount=new Set(h.deployments.map(d=>d.playerId)).size;return {id:h.id,name:h.name,specialtyTag:h.specialtyTag,feeRate:h.feeRate,primeHour:h.primeHour,memberCount,heat:Number((memberCount/this.houseCap).toFixed(1)),liveAuctions:h.auctions.length,liveOrders:h.orders.length};});}
 publicState(pid?:string,currentHouseId?:string):PublicState{let currentHouse:PublicHouseDetail|undefined;if(pid&&currentHouseId){const house=this.houses.get(currentHouseId),deployment=house?.deployments.find(d=>d.playerId===pid);if(house&&deployment){const summary=this.houseSummaries().find(x=>x.id===house.id)!;currentHouse={...summary,auctions:house.auctions.flatMap(a=>{const item=this.items.get(a.itemId);if(!item)return[];const currentBid=a.bids.at(-1)?.amount??0;return [{id:a.id,item:publicItem(item),bids:a.bids,endsAt:a.endsAt,featured:a.featured,currentBid,minBid:currentBid?Math.max(currentBid+10,Math.ceil(currentBid*1.05)):10}];}),orders:house.orders,members:house.deployments.map(d=>({...this.deploymentView(d,house.id),playerName:this.players.get(d.playerId)?.name??"Unknown",rookie:this.players.get(d.playerId)?.rookie??false}))};}}return {houses:this.houseSummaries(),...(currentHouse?{currentHouse}:{}),players:[...this.players.values()].map(({id,name,fame})=>({id,name,fame})),characters:CHARACTERS,abilities:ABILITIES,season:this.season,serverTime:Date.now()};}
}
function validateCredentials(username:string,password:string){const clean=typeof username==="string"?username.trim():"";if(!/^[A-Za-z0-9_]{3,20}$/.test(clean))throw new GameError("Username must be 3-20 characters using letters, numbers, or underscores");if(typeof password!=="string"||password.length<8||password.length>128)throw new GameError("Password must be 8-128 characters");return clean;}
async function hash(password:string,salt:string){return Buffer.from(await scrypt(password,salt,64) as Buffer).toString("hex");}
