import { createServer,type IncomingMessage,type ServerResponse } from "node:http";
import { mkdir,readFile,rename,writeFile } from "node:fs/promises";
import { extname,join,resolve } from "node:path";
import { fileURLToPath } from "node:url";
import { WebSocketServer,WebSocket } from "ws";
import { GameError,GameState } from "./game.js";
import type { ClientMessage,ServerMessage } from "../shared/types.js";
const port=Number(process.env.PORT??3000),dataDir=resolve(process.env.DATA_DIR??"./data"),statePath=join(dataDir,"state.json"),root=fileURLToPath(new URL("../client/",import.meta.url)),seasonHours=Number(process.env.SEASON_LENGTH_HOURS??672);
let saveTimer:ReturnType<typeof setTimeout>|undefined,game:GameState;
const scheduleSave=()=>{if(saveTimer)clearTimeout(saveTimer);saveTimer=setTimeout(()=>void saveState(),2000);};
try{game=await GameState.load(statePath,scheduleSave,seasonHours);console.log(`Loaded state from ${statePath}`);}catch(e){console.warn(`Starting fresh: could not load ${statePath} (${e instanceof Error?e.message:"unknown error"})`);game=new GameState(scheduleSave,seasonHours);}
async function saveState(){if(saveTimer){clearTimeout(saveTimer);saveTimer=undefined;}await mkdir(dataDir,{recursive:true});const temp=`${statePath}.tmp`;await writeFile(temp,JSON.stringify(game.snapshot()),"utf8");await rename(temp,statePath);}
const sessions=new Map<WebSocket,{pid:string;houseId?:string}>();
const http=createServer(async(req,res)=>{try{const url=new URL(req.url??"/","http://localhost");if(req.method==="POST"&&(url.pathname==="/api/register"||url.pathname==="/api/login")){const b=await jsonBody(req),result=url.pathname.endsWith("register")?await game.register(field(b,"username"),field(b,"password")):await game.login(field(b,"username"),field(b,"password"));return json(res,200,result);}if(req.method==="POST"&&url.pathname==="/admin/end-season"){if(!process.env.ADMIN_TOKEN||req.headers.authorization!==`Bearer ${process.env.ADMIN_TOKEN}`)return json(res,403,{error:"Forbidden"});const r=game.forceEndSeason();announce(r.settlements);seasonEnd(r.number);broadcast();await saveState();return json(res,200,{seasonNumber:r.number});}if(req.method!=="GET")return json(res,404,{error:"Not found"});const name=url.pathname==="/"?"index.html":url.pathname.slice(1);if(name.includes(".."))throw new Error("Invalid path");const data=await readFile(join(root,name));res.writeHead(200,{"content-type":extname(name)===".css"?"text/css":extname(name)===".js"?"text/javascript":extname(name)===".png"?"image/png":extname(name)===".svg"?"image/svg+xml":extname(name)===".json"?"application/json":"text/html"});res.end(data);}catch(e){if(req.url?.startsWith("/api/")||req.url?.startsWith("/admin/"))json(res,e instanceof GameError?400:500,{error:e instanceof Error?e.message:"Invalid request"});else{res.writeHead(404);res.end("Not found");}}});
const wss=new WebSocketServer({server:http}),send=(ws:WebSocket,m:ServerMessage)=>{if(ws.readyState===ws.OPEN)ws.send(JSON.stringify(m));};
function state(ws:WebSocket){const s=sessions.get(ws);send(ws,{type:"STATE",publicState:game.publicState(s?.pid,s?.houseId)});}
function privateState(ws:WebSocket,message?:string){const s=sessions.get(ws);if(s&&game.players.has(s.pid))send(ws,message?{type:"PRIVATE",privateState:game.privateState(s.pid,s.houseId),message}:{type:"PRIVATE",privateState:game.privateState(s.pid,s.houseId)});}
let pending=false;function broadcast(){if(pending)return;pending=true;setTimeout(()=>{pending=false;for(const ws of wss.clients)state(ws);},100);}
const houseList=()=>{for(const ws of wss.clients)send(ws,{type:"HOUSE_LIST",houses:game.houseSummaries()});};
const announcement=(message:string)=>{for(const ws of wss.clients)send(ws,{type:"ANNOUNCEMENT",message});};const announce=(notes:string[])=>notes.forEach(announcement);
function seasonEnd(number:number){for(const ws of wss.clients){send(ws,{type:"SEASON_END",number});privateState(ws);}}
wss.on("connection",ws=>{state(ws);ws.on("close",()=>sessions.delete(ws));ws.on("message",raw=>{try{const msg=JSON.parse(raw.toString()) as ClientMessage;if(msg.type==="AUTH"){const auth=game.authenticate(msg.token),first=auth.player?game.deployments(auth.player.id)[0]:undefined;sessions.set(ws,{pid:auth.account.id,...(first?{houseId:first.houseId}:{})});send(ws,{type:"AUTH_OK",playerId:auth.account.id,needsCharacter:!auth.player||!first});send(ws,{type:"HOUSE_LIST",houses:game.houseSummaries()});if(auth.player&&first){const joined=game.join(auth.player.id);send(ws,{type:"WELCOME",playerId:joined.player.id,privateState:game.privateState(joined.player.id,sessions.get(ws)!.houseId,joined.stipendAwarded)});state(ws);}return;}const s=sessions.get(ws);if(!s)throw new GameError("Authenticate first");if(msg.type==="HOUSE_LIST"){send(ws,{type:"HOUSE_LIST",houses:game.houseSummaries()});return;}if(msg.type==="DEPLOY"){game.deploy(s.pid,msg.houseId,msg.characterId);s.houseId=msg.houseId;const joined=game.join(s.pid);send(ws,{type:"WELCOME",playerId:joined.player.id,privateState:game.privateState(joined.player.id,s.houseId,joined.stipendAwarded)});houseList();broadcast();return;}if(msg.type==="REDEPLOY"){game.redeploy(s.pid,msg.characterId,msg.toHouseId);s.houseId=msg.toHouseId;privateState(ws,"Character redeployed; abilities and XP are disabled for 24 hours");houseList();broadcast();return;}if(msg.type==="ENTER_HOUSE"){game.requireDeployment(s.pid,msg.houseId);s.houseId=msg.houseId;privateState(ws);state(ws);return;}if(msg.type==="JOIN"){const joined=game.join(s.pid);send(ws,{type:"WELCOME",playerId:joined.player.id,privateState:game.privateState(joined.player.id,s.houseId,joined.stipendAwarded)});return;}if(!s.houseId)throw new GameError("Enter one of your deployed houses first");if(msg.type==="PING"){send(ws,{type:"PONG",ts:Date.now()});return;}let note:string|undefined;if(msg.type==="OPEN_BOX")note=`Opened ${game.openBox(s.pid).name}`;else if(msg.type==="LIST_ITEM"){const r=game.list(s.pid,s.houseId,msg.itemId,msg.durationSec);if(r.spawned)houseList();}else if(msg.type==="BID")game.bid(s.pid,s.houseId,msg.auctionId,msg.amount);else if(msg.type==="FULFILL_ORDER"){game.fulfill(s.pid,s.houseId,msg.orderId,msg.itemIds);note="Order fulfilled";}else if(msg.type==="USE_ABILITY")note=game.useAbility(s.pid,s.houseId,msg);privateState(ws,note);broadcast();}catch(e){send(ws,{type:"ERROR",message:e instanceof Error?e.message:"Invalid message"});}});});
setInterval(()=>{const notes=game.settle();if(notes.length){for(const ws of wss.clients)privateState(ws);announce(notes);broadcast();}},250);
setInterval(()=>{const r=game.tickSeason();if(r.warning)announcement("Season ends in 5 minutes! Live auctions will be settled.");if(r.ended){announce(r.settlements);seasonEnd(r.ended);broadcast();}},250);
setInterval(()=>{for(const f of game.tickFeatured()){for(const [ws,s] of sessions)if(s.houseId===f.houseId)send(ws,{type:"FEATURED",...f});}broadcast();},1000);
http.listen(port,()=>console.log(`Bid House listening on http://localhost:${port}`));
let closing=false;async function shutdown(){if(closing)return;closing=true;try{await saveState();}catch(e){console.error("Failed to save state during shutdown",e);}http.close(()=>process.exit(0));setTimeout(()=>process.exit(1),5000).unref();}process.on("SIGINT",()=>void shutdown());process.on("SIGTERM",()=>void shutdown());export {http,game,saveState};
function json(res:ServerResponse,status:number,body:unknown){res.writeHead(status,{"content-type":"application/json"});res.end(JSON.stringify(body));}
async function jsonBody(req:IncomingMessage){let raw="";for await(const chunk of req){raw+=String(chunk);if(raw.length>16384)throw new GameError("Request body too large");}try{return JSON.parse(raw) as Record<string,unknown>;}catch{throw new GameError("Invalid JSON");}}
function field(body:Record<string,unknown>,key:string){const value=body[key];if(typeof value!=="string")throw new GameError(`${key} must be a string`);return value;}
