import { spawn } from "node:child_process";
import { mkdtemp,readFile,rm,writeFile } from "node:fs/promises";
import { tmpdir } from "node:os";
import { join } from "node:path";
import WebSocket from "ws";
import { GameError,GameState } from "../server/game.js";
import type { GameSnapshot,Item,Player,ServerMessage } from "../shared/types.js";

const wait=(ms:number)=>new Promise(r=>setTimeout(r,ms));
const check=(ok:unknown,message:string)=>{if(!ok)throw new Error(message);};
const expectError=(fn:()=>unknown,text:string)=>{try{fn();}catch(e){check(e instanceof GameError&&e.message.includes(text),`Expected error containing '${text}', got '${e instanceof Error?e.message:String(e)}'`);return;}throw new Error(`Expected error containing '${text}'`);};
const port=39001,dataDir=await mkdtemp(join(tmpdir(),"bid-house-smoke-")),statePath=join(dataDir,"state.json");
const server=spawn(process.execPath,["dist/server/server.js"],{env:{...process.env,PORT:String(port),DATA_DIR:dataDir,ADMIN_TOKEN:"smoke-admin",SEASON_LENGTH_HOURS:"1",HOUSE_CAP:"1",MAX_DEPLOYS:"3",FEATURED_INTERVAL_MINUTES:"0.001",MOVE_PENALTY_MS:"1000"},stdio:["ignore","pipe","pipe"]});
let log="";server.stdout.on("data",d=>log+=String(d));server.stderr.on("data",d=>log+=String(d));

function item(id:string,owner:string,category:Item["category"]="Art",tier:Item["tier"]=1):Item{return {id,name:`Lot ${id}`,category,tier,tags:["royal"],fake:false,history:[{owner,price:0,ts:Date.now()}]};}
async function account(game:GameState,name:string,character:string){const a=await game.register(name,"correct-horse-password");game.deploy(a.playerId,"house-1",character);game.join(a.playerId);return a.playerId;}

async function modelCoverage(){
 const game=new GameState(()=>{},1000,undefined,{houseCap:1,maxDeploys:3,movePenaltyMs:1000,boxPrice:100});
 const owner=await account(game,"RosterOwner","mara"),p=game.players.get(owner)!;check(p.roster.length===1&&p.roster[0]==="mara","First bidder was not granted free");
 expectError(()=>game.deploy(owner,"house-1","brick"),"do not own");p.coins=1000;while(p.roster.length<6)game.pullBidder(owner);check(p.roster.length===6&&p.coins===250,"Pull cost or duplicate protection failed");expectError(()=>game.pullBidder(owner),"already owned");
 const firstBox=game.openBox(owner);game.list(owner,"house-1",firstBox.id,2);check(game.houses.has("house-2"),"At-cap listing did not spawn a viable house");game.deploy(owner,"house-2","brick");
 const recalled=game.recall(owner,"brick");check(recalled.houseId==="house-2"&&game.deployments(owner).length===1,"Recall did not return bidder to idle roster");expectError(()=>game.deploy(owner,"house-2","brick"),"penalty expires");p.movePenaltyUntil.brick=0;game.deploy(owner,"house-2","brick");game.redeploy(owner,"brick","house-1");expectError(()=>game.redeploy(owner,"brick","house-2"),"penalty expires");
 p.movePenaltyUntil.brick=0;const brick=game.houses.get("house-1")!.deployments.find(d=>d.playerId===owner&&d.characterId==="brick")!;brick.redeployCooldownUntil=0;game.recall(owner,"mara");check(game.deployments(owner).length===1,"Recall changed the wrong deployment");p.movePenaltyUntil.mara=0;game.recall(owner,"brick");check(game.deployments(owner).length===0,"Last-bidder recall was not allowed");

 const xpGame=new GameState(()=>{},1000,undefined,{houseCap:20});const xpPid=await account(xpGame,"XpOwner","june"),xpPlayer=xpGame.players.get(xpPid)!,house=xpGame.houses.get("house-1")!,dep=house.deployments.find(d=>d.playerId===xpPid)!;
 const order=house.orders[0]!,match=item("xp-item",xpPlayer.name,order.template.category??"Art",Math.max(1,order.template.tierMin) as Item["tier"]);if(order.template.tag)match.tags=[order.template.tag];match.fake=false;xpGame.items.set(match.id,match);xpPlayer.inventory.push(match.id);const oldAccountXp=xpPlayer.xp;xpGame.fulfill(xpPid,"house-1",order.id,[match.id]);check(dep.xp===order.reward.xp&&xpPlayer.xp===oldAccountXp,"Order XP was not credited only to deployment");
 dep.xp=300;check(GameState.levelForXp(dep.xp)===3&&GameState.cooldownMultiplier(dep.xp)===.96,"Level curve or cooldown multiplier failed");const beforeAbility=Date.now();xpGame.useAbility(xpPid,"house-1",{type:"USE_ABILITY",abilityId:"tempo"});const cooldown=xpPlayer.abilities.tempo!.readyAt-beforeAbility;check(cooldown>=95900&&cooldown<=96100,"Ability cooldown did not use bidder level multiplier");
}

async function ledgerOrdersPrivacyAndMigration(){
 const game=new GameState(()=>{},1000,undefined,{houseCap:1,maxDeploys:3});const seller=await account(game,"LedgerSeller","mara"),buyer=await account(game,"LedgerBuyer","june"),outsider=await account(game,"LedgerOutsider","rex");const sellerP=game.players.get(seller)!,buyerP=game.players.get(buyer)!;buyerP.coins=10000;
 const seed=game.openBox(seller);game.list(seller,"house-1",seed.id,2);sellerP.roster.push("brick");game.deploy(seller,"house-2","brick");
 const memberOrders=game.memberOrders(seller),allowed=new Set(game.deployments(seller).map(d=>d.houseId));check(memberOrders.length===12&&memberOrders.every(x=>allowed.has(x.houseId)),"Member orders did not aggregate exactly two deployed houses");game.recall(outsider,"rex");check(game.memberOrders(outsider).length===0,"Outsider received member orders");
 const h=game.houses.get("house-1")!,saleItem=item("sale-private",sellerP.name,"Tech",2);game.items.set(saleItem.id,saleItem);h.auctions.push({id:"sale-1",itemId:saleItem.id,sellerId:seller,bids:[{playerId:buyer,amount:200,ts:1}],endsAt:1,featured:true,listingFeePaid:1});const notices=game.settle(2,1234);check(notices.length===1&&notices[0]!.paid,"Paid settlement missing");
 const summary=game.marketSummary(2000),tech=summary.templates.find(x=>x.templateKey==="Tech:2")!;check(summary.templates.length===20&&tech.count===1&&tech.averagePrice===200&&tech.lastPrice===200,"Ledger aggregate or zero-template catalog failed");
 game.marketLedger.push({saleId:"sale-2",templateKey:"Tech:2",price:300,tags:["neon"],settledAt:2234,season:game.season.number});game.settledAuctionIds.add("sale-2");const page1=game.marketHistory("Tech:2",undefined,1),page2=game.marketHistory("Tech:2",page1.nextCursor,1);check(page1.rows[0]?.saleId==="sale-2"&&page2.rows[0]?.saleId==="sale-1"&&!page2.nextCursor,"Ledger pagination order failed");
 h.auctions.push({id:"sale-1",itemId:"missing",sellerId:seller,bids:[],endsAt:1,featured:false,listingFeePaid:1});game.settle(2,3000);check(game.marketLedger.filter(x=>x.saleId==="sale-1").length===1,"Settlement dedupe failed");
 const pub=game.publicState(buyer,"house-1"),frame=JSON.stringify(pub.currentHouse?.auctions);check(Object.keys(pub.players[0]!).sort().join(",")==="fame,id,name","Global player projection is not minimal");check(!frame.includes("LedgerSeller")&&!frame.includes('"history"')&&!frame.includes('"fake"')&&!frame.includes('"sellerId"'),"Public auction projection leaked provenance or seller identity");
 const snapshot=game.snapshot();await writeFile(statePath,JSON.stringify(snapshot),"utf8");const restored=await GameState.load(statePath,()=>{},1000);check(restored.marketLedger.length===2&&restored.marketSummary().templates.find(x=>x.templateKey==="Tech:2")?.count===2,"Schema v3 reload lost ledger");restored.forceEndSeason();check(restored.marketLedger.length===0&&restored.marketSummary().season===snapshot.season.number+1,"Season reset did not clear ledger");
 const legacyPlayer=structuredClone(snapshot.players[0]!) as Player;delete (legacyPlayer as Partial<Player>).roster;delete (legacyPlayer as Partial<Player>).movePenaltyUntil;const v2={...snapshot,schemaVersion:2,players:[legacyPlayer],marketLedger:undefined,settledAuctionIds:undefined};await writeFile(statePath,JSON.stringify(v2),"utf8");const migrated=await GameState.load(statePath,()=>{},1000);const migratedPlayer=migrated.players.get(legacyPlayer.id)!;check(migratedPlayer.roster.includes(legacyPlayer.characterId)&&migrated.deployments(legacyPlayer.id).every(d=>migratedPlayer.roster.includes(d.characterId)),"v2 roster migration failed");
 await writeFile(statePath,JSON.stringify({...v2,schemaVersion:99}),"utf8");let loud=false;try{await GameState.load(statePath);}catch(e){loud=e instanceof Error&&e.message.includes("Unsupported");}check(loud,"Unsupported migration did not fail loudly");
 console.log("MODEL PASS: roster/pulls/ownership, recall and move lock, per-bidder XP/levels, ledger aggregate/pagination/dedupe/reset, member-order geography, privacy projections, and migrations.");
}

async function registerHttp(name:string){const response=await fetch(`http://127.0.0.1:${port}/api/register`,{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({username:name,password:"correct-horse-password"})});check(response.ok,`HTTP registration failed for ${name}`);return await response.json() as {token:string;playerId:string};}
async function socket(token:string){const ws=new WebSocket(`ws://127.0.0.1:${port}`),messages:ServerMessage[]=[];ws.on("message",raw=>messages.push(JSON.parse(raw.toString()) as ServerMessage));await new Promise<void>((resolve,reject)=>{ws.once("open",resolve);ws.once("error",reject);});ws.send(JSON.stringify({type:"AUTH",token}));await wait(100);return {ws,messages,send:(value:unknown)=>ws.send(JSON.stringify(value))};}
const privateMessages=(xs:ServerMessage[])=>xs.filter((x):x is Extract<ServerMessage,{type:"PRIVATE"}>=>x.type==="PRIVATE");
const stateMessages=(xs:ServerMessage[])=>xs.filter((x):x is Extract<ServerMessage,{type:"STATE"}>=>x.type==="STATE");
async function websocketCoverage(){
 const sa=await registerHttp("WireSeller"),ba=await registerHttp("WireBuyer"),oa=await registerHttp("WireOutsider");const seller=await socket(sa.token),seller2=await socket(sa.token),buyer=await socket(ba.token),outsider=await socket(oa.token);
 seller.send({type:"DEPLOY",houseId:"house-1",characterId:"mara"});buyer.send({type:"DEPLOY",houseId:"house-1",characterId:"june"});await wait(120);seller.send({type:"OPEN_BOX"});await wait(100);const privateFrame=privateMessages(seller.messages).at(-1);check(privateFrame&&privateFrame.privateState.items.length>0,"OPEN_BOX did not refresh private state");if(!privateFrame)throw new Error("Missing private frame");const opened=privateFrame.privateState.items.at(-1)!;seller.send({type:"LIST_ITEM",itemId:opened.id,durationSec:2});await wait(150);outsider.send({type:"DEPLOY",houseId:"house-2",characterId:"rex"});await wait(100);const auction=stateMessages(seller.messages).reverse().find(x=>x.publicState.currentHouse?.auctions.length)?.publicState.currentHouse?.auctions[0];check(auction,"Listed auction not visible to member");buyer.send({type:"BID",auctionId:auction!.id,amount:10});await wait(5500);
 const sold=(xs:ServerMessage[])=>xs.some(x=>x.type==="ANNOUNCEMENT"&&x.message.includes("sold for 10"));check(sold(seller.messages)&&sold(buyer.messages)&&!sold(outsider.messages),"Sale announcement escaped house/participant scope");check(privateMessages(seller2.messages).length>=2,"Second account socket was not refreshed after mutations");const stateFrame=JSON.stringify(stateMessages(seller.messages).find(x=>x.publicState.currentHouse?.auctions.length)?.publicState.currentHouse?.auctions);check(!stateFrame.includes("WireSeller")&&!stateFrame.includes('"history"')&&!stateFrame.includes('"fake"')&&!stateFrame.includes('"sellerId"'),"Wire public frame leaked seller provenance");for(const x of [seller,seller2,buyer,outsider])x.ws.close();console.log("WS PASS: sale notes scoped to house/participants, public DTO sanitized, and all account sessions refreshed.");
}

async function run(){try{while(!log.includes("listening")){if(server.exitCode!==null)throw new Error(`Server exited early: ${log}`);await wait(20);}const initial=await fetch(`http://127.0.0.1:${port}`),html=await initial.text(),sourceHtml=await readFile("src/client/index.html","utf8");check(initial.ok&&html.includes('href="styles.css"')&&sourceHtml.includes('src="client.js"'),"UI bundle references missing");console.log("UI BUNDLE PASS: static shell served.");await modelCoverage();await ledgerOrdersPrivacyAndMigration();await websocketCoverage();console.log("SMOKE PASS: all legacy-compatible and five-tab server foundation assertions passed.");}finally{if(server.exitCode===null){server.kill("SIGTERM");await Promise.race([new Promise<void>(r=>server.once("exit",()=>r())),wait(5000)]);}await rm(dataDir,{recursive:true,force:true});}}
run().catch(e=>{console.error("SMOKE FAIL:",e);console.error(log);process.exitCode=1;});
