import type { AbilityDefinition, Character, PrivateState, PublicAuction, PublicState, ServerMessage } from "../shared/types.js";
const $=<T extends HTMLElement>(id:string)=>document.getElementById(id) as T;
let socket:WebSocket;let publicState:PublicState|undefined;let privateState:PrivateState|undefined;let selectedAuction:string|undefined;let characters:Character[]=[];let registerMode=false;let authenticating=false;
const esc=(s:string)=>s.replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[c]!));
const send=(m:object)=>socket?.readyState===WebSocket.OPEN&&socket.send(JSON.stringify(m));
function toast(message:string,error=false){const e=document.createElement("div");e.className=`toast${error?" error":""}`;e.textContent=message;$("toasts").append(e);setTimeout(()=>e.remove(),3500)}
function show(view:"account"|"character"|"game"){for(const id of ["accountView","characterView","gameView"])$(id).classList.toggle("hidden",id!==`${view}View`);}
function connect(){socket=new WebSocket(`${location.protocol==="https:"?"wss":"ws"}://${location.host}`);socket.onopen=()=>{$("connection").textContent="Connected";const token=localStorage.getItem("bidHouseToken");if(token){authenticating=true;send({type:"AUTH",token});}else show("account");};socket.onclose=()=>{$("connection").textContent="Reconnecting…";setTimeout(connect,1000)};socket.onmessage=e=>handle(JSON.parse(String(e.data)) as ServerMessage)}
function handle(m:ServerMessage){if(m.type==="AUTH_OK"){authenticating=false;if(m.needsCharacter)show("character");}else if(m.type==="WELCOME"){privateState=m.privateState;show("game");render();}else if(m.type==="STATE"){publicState=m.publicState;characters=m.publicState.characters;populateCharacters();render();renderSeason();}else if(m.type==="PRIVATE"){privateState=m.privateState;if(m.message)toast(m.message);render();}else if(m.type==="ERROR"){if(authenticating){authenticating=false;localStorage.removeItem("bidHouseToken");show("account");}toast(m.message,true);}else if(m.type==="ANNOUNCEMENT")toast(m.message);else if(m.type==="SEASON_END")toast(`Season ${m.number-1} ended. Welcome to Season ${m.number}!`)}
function populateCharacters(){const sel=$("character") as HTMLSelectElement;if(sel.options.length||!characters.length)return;for(const c of characters)sel.add(new Option(c.name,c.id));showCharacter()}
function showCharacter(){const c=characters.find(x=>x.id===($("character") as HTMLSelectElement).value);$("characterDetail").textContent=c?`${c.passive} Abilities: ${[c.mainAbility,...c.traits].join(", ")}`:""}
function itemTags(tags:string[]){return `<div class="tags">${tags.map(t=>`<span class="tag">${esc(t)}</span>`).join("")}</div>`}
function render(){if(!privateState||!publicState)return;const p=privateState.player,c=publicState.characters.find(x=>x.id===p.characterId)!;$("wallet").textContent=`${p.coins} coins · ${p.xp} XP · ${p.fame} fame`;$("identity").innerHTML=`<strong>${esc(c.name)}</strong><br><span class="muted">${esc(c.passive)} · ${p.boxes} free boxes</span>`;
  $("inventory").innerHTML=privateState.items.length?privateState.items.map(i=>`<article class="card"><div class="row"><strong>${esc(i.name)}</strong><span>T${i.tier}</span></div><p class="muted">${i.category} · ${i.fake?"FAKE":"AUTHENTIC"}</p>${itemTags(i.tags)}<div class="bidline"><select id="dur-${i.id}"><option value="30">30 sec</option><option value="60">1 min</option><option value="300">5 min</option></select><button data-list="${i.id}">List</button></div></article>`).join(""):"<p class='muted'>Open a box or win an auction.</p>";
  $("inventory").querySelectorAll<HTMLButtonElement>("[data-list]").forEach(b=>b.onclick=()=>send({type:"LIST_ITEM",itemId:b.dataset.list,durationSec:Number(($("dur-"+b.dataset.list) as HTMLSelectElement).value)}));
  const allIds=[c.mainAbility,...c.traits];$("abilities").innerHTML=allIds.map(id=>{const d=publicState!.abilities.find(a=>a.id===id)!,ready=Math.max(0,(p.abilities[id]?.readyAt??0)-Date.now());return `<button data-ability="${id}" title="${esc(d.description)}" ${ready>0?"disabled":""}>${esc(d.name)}${ready>0?` ${Math.ceil(ready/1000)}s`:""}</button>`}).join("");$("abilities").querySelectorAll<HTMLButtonElement>("button").forEach(b=>b.onclick=()=>useAbility(b.dataset.ability!));
  $("auctions").innerHTML=publicState.auctions.length?publicState.auctions.map(auctionCard).join(""):"<p class='muted'>No live lots. List something from your cabinet.</p>";$("auctions").querySelectorAll<HTMLButtonElement>("[data-bid]").forEach(b=>b.onclick=()=>{const id=b.dataset.bid!,input=$("bid-"+id) as HTMLInputElement;send({type:"BID",auctionId:id,amount:Number(input.value)})});
  $("orders").innerHTML=publicState.orders.map(o=>{const match=privateState!.items.find(i=>(!o.template.category||i.category===o.template.category)&&(!o.template.tag||i.tags.includes(o.template.tag))&&i.tier>=o.template.tierMin&&(o.template.fakeAllowed||!i.fake));const need=o.template.category??`#${o.template.tag}`;return `<article class="card"><strong>${esc(need)} · Tier ${o.template.tierMin}+</strong><p class="muted">${o.template.fakeAllowed?"Fakes accepted":"Authentic only"} · ${o.reward.coins} coins / ${o.reward.fame} fame</p><button data-order="${o.id}" data-item="${match?.id??""}" ${match?"":"disabled"}>${match?"Fulfill":"No match"}</button></article>`}).join("");
  $("orders").querySelectorAll<HTMLButtonElement>("[data-order]").forEach(b=>b.onclick=()=>send({type:"FULFILL_ORDER",orderId:b.dataset.order,itemIds:[b.dataset.item]}));
}
function auctionCard(a:PublicAuction){const peek=privateState?.peeked[a.item.id],top=a.bids.at(-1),mine=top?.playerId===privateState?.player.id;return `<article class="card ${a.featured?"featured":""}" data-auction="${a.id}"><div class="row"><strong>${esc(a.item.name)}</strong><span>${a.featured?"★ ":""}T${a.item.tier}</span></div>${itemTags(a.item.tags)}<p class="muted">${a.item.category} · Seller hidden · ${peek===undefined?"Authenticity unknown":peek?"Peek: FAKE":"Peek: AUTHENTIC"}</p><div class="row"><span>${a.currentBid||"No bids"}${a.currentBid?" coins":""}${mine?" · You lead":""}</span><strong class="timer" data-end="${a.endsAt}"></strong></div><div class="bidline"><input id="bid-${a.id}" type="number" min="${a.minBid}" value="${a.minBid}"><button data-bid="${a.id}">Bid</button></div></article>`}
function useAbility(id:string){const d=publicState!.abilities.find(x=>x.id===id) as AbilityDefinition;const auctions=publicState!.auctions;if(["peek","reveal","shield","refund","tax","block"].includes(d.kind)){if(!auctions.length)return toast("No live auction to target",true);const a=auctions.find(x=>x.id===selectedAuction)??auctions[0]!;selectedAuction=a.id;let targetPlayerId:string|undefined;if(d.kind==="block")targetPlayerId=a.bids.find(b=>b.playerId!==privateState!.player.id)?.playerId??publicState!.players.find(x=>x.id!==privateState!.player.id)?.id;send({type:"USE_ABILITY",abilityId:id,auctionId:a.id,targetPlayerId});}else send({type:"USE_ABILITY",abilityId:id})}
function renderSeason(){if(!publicState)return;const ms=Math.max(0,publicState.season.endsAt-Date.now()),days=Math.floor(ms/86400000),hours=Math.floor(ms%86400000/3600000),minutes=Math.floor(ms%3600000/60000);$("season").textContent=`Season ${publicState.season.number} — ends in ${days}d ${hours}h ${minutes}m`;}
$("accountForm").addEventListener("submit",async e=>{e.preventDefault();const username=($("username") as HTMLInputElement).value,password=($("password") as HTMLInputElement).value;try{const response=await fetch(registerMode?"/api/register":"/api/login",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({username,password})});const data=await response.json() as {token?:string;error?:string};if(!response.ok||!data.token)throw new Error(data.error??"Authentication failed");localStorage.setItem("bidHouseToken",data.token);authenticating=true;send({type:"AUTH",token:data.token});}catch(error){toast(error instanceof Error?error.message:"Authentication failed",true);}});
$("accountToggle").onclick=()=>{registerMode=!registerMode;$("accountTitle").textContent=registerMode?"Register":"Log in";$("accountSubmit").textContent=registerMode?"Register":"Log in";$("accountToggle").textContent=registerMode?"Already registered? Log in":"Need an account? Register";($("password") as HTMLInputElement).autocomplete=registerMode?"new-password":"current-password";};
$("characterForm").addEventListener("submit",e=>{e.preventDefault();send({type:"JOIN",characterId:($("character") as HTMLSelectElement).value})});$("character").addEventListener("change",showCharacter);$("openBox").onclick=()=>send({type:"OPEN_BOX"});
setInterval(()=>{document.querySelectorAll<HTMLElement>(".timer").forEach(e=>e.textContent=`${Math.max(0,Math.ceil((Number(e.dataset.end)-Date.now())/1000))}s`);renderSeason();},250);connect();
