import type {AbilityDefinition,Character,Deployment,HouseSummary,Item,Order,PrivateState,PublicAuction,PublicState,ServerMessage} from "../shared/types.js";

const $=<T extends HTMLElement>(id:string)=>document.getElementById(id) as T;
const asset=(path:string)=>`/client-assets/${path}`;
const icon=(path:string,label="",className="")=>`<span class="mask-icon ${className}" style="--icon:url('${asset(path)}')" ${label?`role="img" aria-label="${esc(label)}"`:'aria-hidden="true"'}></span>`;
const esc=(value:string)=>value.replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[c]!));
const fmt=(value:number)=>new Intl.NumberFormat("en-US").format(value);
let socket:WebSocket,state:PublicState|undefined,priv:PrivateState|undefined,characters:Character[]=[],registerMode=false,authenticating=false,pendingHouse:string|undefined,pendingCharacterId:string|undefined,inGame=false,selectedCharacter=0,inventoryFilter="all",carouselScrollTimer:ReturnType<typeof setTimeout>|undefined;
const priorBids=new Map<string,number>(),priorEnds=new Map<string,number>();

function send(message:object){if(socket?.readyState===WebSocket.OPEN)socket.send(JSON.stringify(message));}
function show(view:"account"|"character"|"house"|"game"){
  for(const id of ["accountView","characterView","houseView","gameView"])$(id).classList.toggle("hidden",id!==`${view}View`);
  const hall=view==="game";$('topbar').classList.toggle("hidden",!hall);$('mobileNav').classList.toggle("hidden",!hall);
}
function toast(message:string,type:"success"|"error"|"info"="info"){
  const el=document.createElement("div");el.className=`toast ${type}`;el.textContent=message;$('toasts').append(el);setTimeout(()=>el.remove(),4000);
}
function connect(){
  socket=new WebSocket(`${location.protocol==="https:"?"wss":"ws"}://${location.host}`);
  socket.onopen=()=>{$('connection').textContent="Connected";const token=localStorage.getItem("bidHouseToken");if(token){authenticating=true;send({type:"AUTH",token});}else show("account");};
  socket.onclose=()=>{$('connection').textContent="Reconnecting";setTimeout(connect,1000);};
  socket.onmessage=event=>handle(JSON.parse(String(event.data)) as ServerMessage);
}
function handle(message:ServerMessage){
  if(message.type==="AUTH_OK"){
    authenticating=false;
    if(message.needsCharacter){selectedCharacter=0;renderCharacters();show("character");}
  }else if(message.type==="HOUSE_LIST"){
    if(state)state.houses=message.houses;renderHouses();renderSwitcher();
  }else if(message.type==="WELCOME"){
    priv=message.privateState;if(priv.stipendAwarded!==undefined)toast(`Catch-up stipend: +${priv.stipendAwarded} coins`,"success");inGame=true;show("game");render();
  }else if(message.type==="STATE"){
    captureAuctionChanges(message.publicState);state=message.publicState;characters=state.characters;renderCharacters();renderHouses();renderSwitcher();render();renderSeason();
  }else if(message.type==="PRIVATE"){
    const oldIds=new Set(priv?.items.map(item=>item.id)??[]);priv=message.privateState;const revealed=priv.items.find(item=>!oldIds.has(item.id));if(message.message)toast(message.message,"success");if(revealed&&message.message?.startsWith("Opened"))showBoxReveal(revealed);renderHouses();renderSwitcher();render();
  }else if(message.type==="FEATURED")toast("A featured lot has taken the spotlight","success");
  else if(message.type==="ERROR"){
    if(authenticating){localStorage.removeItem("bidHouseToken");show("account");}$('authError').textContent=message.message;toast(message.message,"error");
  }else if(message.type==="ANNOUNCEMENT")toast(message.message);
  else if(message.type==="SEASON_END")showSeasonEnd(message.number);
}
function captureAuctionChanges(next:PublicState){
  const current=state?.currentHouse?.auctions??[],incoming=next.currentHouse?.auctions??[];
  if(current.some(a=>!incoming.some(n=>n.id===a.id))){const v=$('settleVignette');v.classList.remove("hidden");setTimeout(()=>v.classList.add("hidden"),180);}
  for(const auction of incoming){const oldBid=priorBids.get(auction.id),oldEnd=priorEnds.get(auction.id);if(oldBid!==undefined&&auction.currentBid>oldBid)setTimeout(()=>document.querySelector(`[data-auction-card="${auction.id}"]`)?.classList.add("bid-pulse"),0);if(oldEnd!==undefined&&auction.endsAt-oldEnd>=4000)setTimeout(()=>showExtension(auction.id),0);priorBids.set(auction.id,auction.currentBid);priorEnds.set(auction.id,auction.endsAt);}
}

function renderCharacters(scrollSelected=false){
  if(!characters.length)return;selectedCharacter=(selectedCharacter+characters.length)%characters.length;
  $('characterCarousel').innerHTML=characters.map((c,index)=>`<article class="character-card ${index===selectedCharacter?"selected":""}" data-character-index="${index}"><img src="${asset(`characters/${c.id}.png`)}" alt="Portrait of ${esc(c.name)}"><div class="character-copy"><p class="kicker">BIDDER ${String(index+1).padStart(2,"0")}</p><h2>${esc(c.name)}</h2><p class="passive">${esc(c.passive)}</p><p class="muted">Signature: ${esc(ability(c.mainAbility)?.name??c.mainAbility)}</p><div class="trait-row">${c.traits.map(id=>`<span class="tag">${esc(ability(id)?.name??id)}</span>`).join("")}</div></div></article>`).join("");
  $('carouselCount').textContent=`${selectedCharacter+1} / ${characters.length}`;
  const carousel=$('characterCarousel');
  carousel.querySelectorAll<HTMLElement>('[data-character-index]').forEach(card=>card.onclick=()=>{selectedCharacter=Number(card.dataset.characterIndex);renderCharacters(true);});
  carousel.onscroll=()=>{clearTimeout(carouselScrollTimer);carouselScrollTimer=setTimeout(()=>{const center=carousel.getBoundingClientRect().left+carousel.clientWidth/2,cards=Array.from(carousel.querySelectorAll<HTMLElement>('[data-character-index]')),closest=cards.reduce((best,card)=>Math.abs(card.getBoundingClientRect().left+card.clientWidth/2-center)<Math.abs(best.getBoundingClientRect().left+best.clientWidth/2-center)?card:best);selectedCharacter=Number(closest.dataset.characterIndex);cards.forEach(card=>card.classList.toggle("selected",card===closest));$('carouselCount').textContent=`${selectedCharacter+1} / ${characters.length}`;},120);};
  if(scrollSelected)requestAnimationFrame(()=>carousel.querySelector<HTMLElement>(`[data-character-index="${selectedCharacter}"]`)?.scrollIntoView({behavior:matchMedia('(prefers-reduced-motion: reduce)').matches?"auto":"smooth",block:"nearest",inline:"center"}));
}
function ability(id:string){return state?.abilities.find(entry=>entry.id===id);}
function glyphs(name:string){const names=["anchor","book","coin","comet","crown","flame","gavel","gem","key","mask","moon","star"],hash=[...name].reduce((sum,c)=>((sum*31+c.charCodeAt(0))>>>0),7);return [names[hash%names.length]!,names[Math.floor(hash/names.length)%names.length]!];}
function tint(specialty:string|null){const colors=["#D4A24E","#7E5CE0","#5E8FD4","#5C9E6E","#C476E8"],key=specialty??"all";return colors[[...key].reduce((n,c)=>n+c.charCodeAt(0),0)%colors.length]!;}
function sigil(house:HouseSummary){const [a,b]=glyphs(house.name),color=tint(house.specialtyTag);return `<span class="sigil" style="color:${color}" role="img" aria-label="${esc(house.name)} sigil">${icon("sigils/sigil-base.svg")}${icon(`sigils/glyph-${a}.svg`,"","glyph-a")}${icon(`sigils/glyph-${b}.svg`,"","glyph-b")}</span>`;}
function heatMeter(heat:number){const active=Math.max(0,Math.min(5,Math.ceil(heat*5)));return `<div class="heat-meter" aria-label="Heat ${active} of 5">${Array.from({length:5},(_,i)=>`<i class="${i<active?"on":""}"></i>`).join("")}</div>`;}
function renderHouses(){
  if(!state)return;const mine=priv?.deployments??[];
  $('deployments').innerHTML=`<div class="deployment-title"><strong>Your deployments</strong><span class="muted">${mine.length}/3 slots</span></div>${mine.length?mine.map(deploymentCard).join(""):`<p class="muted">Choose a house below to make your first deployment.</p>`}`;
  $('deployments').querySelectorAll<HTMLSelectElement>('[data-redeploy]').forEach(select=>select.onchange=()=>{if(select.value)send({type:"REDEPLOY",characterId:select.dataset.redeploy,toHouseId:select.value});});
  $('houses').innerHTML=state.houses.map(h=>houseCard(h,mine.some(d=>d.houseId===h.id))).join("");
  $('houses').querySelectorAll<HTMLButtonElement>('[data-enter]').forEach(button=>button.onclick=()=>send({type:"ENTER_HOUSE",houseId:button.dataset.enter}));
  $('houses').querySelectorAll<HTMLButtonElement>('[data-deploy]').forEach(button=>button.onclick=()=>{pendingHouse=button.dataset.deploy;if(pendingCharacterId){send({type:"DEPLOY",houseId:pendingHouse,characterId:pendingCharacterId});pendingHouse=undefined;pendingCharacterId=undefined;}else{selectedCharacter=0;renderCharacters();show("character");}});
}
function deploymentCard(d:Deployment){const c=characters.find(x=>x.id===d.characterId),house=state!.houses.find(h=>h.id===d.houseId),cool=d.redeployCooldownUntil>Date.now()?shortTime(d.redeployCooldownUntil-Date.now()):"Ready";return `<article class="deployment"><img src="${asset(`characters/${c?.id??d.characterId}.png`)}" alt=""><div><strong>${esc(c?.name??d.characterId)}</strong><small class="muted">${esc(house?.name??"House")} · <span class="cooldown">${cool}</span></small></div><select data-redeploy="${d.characterId}" aria-label="Redeploy ${esc(c?.name??d.characterId)}"><option value="">Move to another house…</option>${state!.houses.filter(h=>h.id!==d.houseId).map(h=>`<option value="${h.id}">${esc(h.name)}</option>`).join("")}</select></article>`;}
function houseCard(h:HouseSummary,active:boolean){const deployed=active||state?.currentHouse?.id===h.id,full=h.heat>=1,canDeploy=(priv?.deployments.length??0)<3,pendingName=characters.find(c=>c.id===pendingCharacterId)?.name;return `<article class="house-card"><div class="house-head">${sigil(h)}<div><span class="specialty">${esc(h.specialtyTag??"Open specialty")}</span><h3>${esc(h.name)}</h3></div></div><div class="house-facts"><span>FEE<b>${Math.round(h.feeRate*100)}%</b></span><span>PRIME<b>${String(h.primeHour).padStart(2,"0")}:00</b></span><span>MEMBERS<b>${h.memberCount}</b></span></div><div><div class="heat-label"><span>HOUSE HEAT</span><span>${Math.round(h.heat*100)}%</span></div>${heatMeter(h.heat)}</div><div class="live-counts"><span><b>${h.liveAuctions}</b> live lots</span><span><b>${h.liveOrders}</b> orders</span></div>${deployed?`<button class="primary" data-enter="${h.id}">Enter house</button>`:canDeploy&&!full?`<button class="${pendingName?"primary":""}" data-deploy="${h.id}">${pendingName?`Deploy ${esc(pendingName)} here`:`Deploy character →`}</button>`:`<button disabled>${full?"House full":"Deploy slots full"}</button>`}</article>`;}

function renderSwitcher(){if(!state)return;const select=$<HTMLSelectElement>('houseSwitcher'),mine=priv?.deployments??[];select.innerHTML=`<option value="">Browse houses</option>${mine.map(d=>{const h=state!.houses.find(x=>x.id===d.houseId),c=characters.find(x=>x.id===d.characterId),heat=h?"●".repeat(Math.max(1,Math.ceil(h.heat*3))):"";return `<option value="${d.houseId}" ${state!.currentHouse?.id===d.houseId?"selected":""}>${heat} ${esc(h?.name??"House")} · ${esc(c?.name??d.characterId)}</option>`;}).join("")}`;}
function currentDeployment(){if(!state?.currentHouse||!priv)return undefined;return priv.deployments.find(d=>d.houseId===state!.currentHouse!.id)||priv.deployments.find(d=>state!.currentHouse!.members.some(m=>m.playerId===priv!.player.id&&m.characterId===d.characterId));}
function render(){
  if(!state||!priv)return;$('coins').textContent=fmt(priv.player.coins);$('fame').textContent=fmt(priv.player.fame);$('xp').textContent=fmt(priv.player.xp);$('openBox').toggleAttribute("disabled",priv.player.coins<100&&priv.player.boxes===0);$('boxPrice').textContent=priv.player.boxes?`${priv.player.boxes} complimentary`:`100 coins`;
  if(!state.currentHouse)return;const h=state.currentHouse,dep=currentDeployment(),c=characters.find(x=>x.id===dep?.characterId);
  if(c&&dep)renderIdentity(c,dep);renderAbilities(c,dep);renderInventory();renderAuctions();renderOrders();renderLedger();
}
function renderIdentity(c:Character,dep:Deployment){const pct=Math.min(100,priv!.player.xp%100),cool=dep.redeployCooldownUntil>Date.now()?`Redeploy lock · ${shortTime(dep.redeployCooldownUntil-Date.now())}`:"";$('identity').innerHTML=`<div class="character-summary"><div class="portrait-wrap" style="--xp:${pct}%"><div class="xp-ring"></div><img src="${asset(`characters/${c.id}.png`)}" alt="${esc(c.name)}"></div><div><p class="kicker">YOUR BIDDER</p><h2>${esc(c.name)}</h2><p class="passive-copy">${esc(c.passive)}</p>${cool?`<div class="redeploy-cooldown timer">${cool}</div>`:""}</div></div>`;}
const kindIcon=(kind:string)=>kind==="reveal"?"appraise":kind==="coin"?"coin-ability":kind;
function renderAbilities(c:Character|undefined,dep:Deployment|undefined){if(!c||!dep)return;const blocked=dep.redeployCooldownUntil>Date.now(),ids=[c.mainAbility,...c.traits];$('abilities').innerHTML=ids.map(id=>{const def=ability(id)!,slot=priv!.player.abilities[id],left=def.maxUses===undefined?3:Math.max(0,def.maxUses-(slot?.uses??0)),remain=Math.max(0,(slot?.readyAt??0)-Date.now()),ratio=Math.min(100,remain/def.cooldownMs*100);return `<button class="ability" data-ability="${id}" title="${esc(def.description)}" ${blocked||remain>0||left===0?"disabled":""} style="--cool:${ratio}%"><span class="cooldown-sweep"></span><span class="pips">${Array.from({length:left},()=>"<i></i>").join("")}</span>${icon(`icons/${kindIcon(def.kind)}.svg`)}<span class="ability-name">${esc(def.name)}</span>${remain?`<small class="cooldown">${Math.ceil(remain/1000)}s</small>`:""}</button>`;}).join("");$('abilities').querySelectorAll<HTMLButtonElement>('[data-ability]').forEach(button=>button.onclick=()=>openAbility(button.dataset.ability!));}
function art(category:string,tier:number){return asset(`items/art-${category.toLowerCase()}-${tier}.png`);}
function renderInventory(){const filters=["all",...new Set(priv!.items.map(i=>i.category.toLowerCase()))];if(!filters.includes(inventoryFilter))inventoryFilter="all";$('inventoryFilters').innerHTML=filters.map(f=>`<button class="${f===inventoryFilter?"active":""}" data-filter="${f}">${f}</button>`).join("");$('inventoryFilters').querySelectorAll<HTMLButtonElement>('[data-filter]').forEach(b=>b.onclick=()=>{inventoryFilter=b.dataset.filter!;renderInventory();});const items=priv!.items.filter(i=>inventoryFilter==="all"||i.category.toLowerCase()===inventoryFilter);$('inventoryCount').textContent=String(priv!.items.length);$('inventory').innerHTML=items.length?items.map(i=>`<button class="item-tile t${i.tier}" data-item="${i.id}" title="${esc(i.name)}"><img src="${art(i.category,i.tier)}" alt=""><span>${esc(i.name)}</span>${i.fake?`<img class="fake-ribbon" src="${asset("frames/ribbon-fake-owner.svg")}" alt="Unverified — visible only to you">`:""}</button>`).join(""):`<p class="empty">No matching items.</p>`;$('inventory').querySelectorAll<HTMLButtonElement>('[data-item]').forEach(b=>b.onclick=()=>openItem(b.dataset.item!));}
function itemFrame(item:{category:string;tier:number;name:string}){return `<div class="item-art-frame t${item.tier}"><img src="${art(item.category,item.tier)}" alt="${esc(item.name)}"></div>`;}
function renderAuctions(){const auctions=state!.currentHouse!.auctions.slice().sort((a,b)=>a.endsAt-b.endsAt),featured=auctions.find(a=>a.featured),regular=auctions.filter(a=>!a.featured);$('featured').innerHTML=featured?featuredCard(featured):"";$('auctions').innerHTML=regular.length?regular.map(auctionCard).join(""):(featured?"":`<p class="empty">The floor is quiet. Check back when a lot is listed.</p>`);wireAuctions();}
function featuredCard(a:PublicAuction){const peek=priv!.peeked[a.item.id];return `<article class="featured-hero" data-auction-card="${a.id}"><span class="featured-badge">${icon("icons/featured.svg")}FEATURED</span>${itemFrame(a.item)}${peek!==undefined?`<img class="appraised-seal" src="${asset("frames/seal-appraised.svg")}" alt="Privately appraised: ${peek?"fake":"authentic"}">`:""}<div class="featured-copy"><h2>${esc(a.item.name)}</h2>${tagList(a.item.tags)}${bidPanel(a,true)}</div></article>`;}
function auctionCard(a:PublicAuction){const peek=priv!.peeked[a.item.id];return `<article class="auction-card" data-auction-card="${a.id}">${itemFrame(a.item)}${peek!==undefined?`<img class="appraised-seal" src="${asset("frames/seal-appraised.svg")}" alt="Privately appraised: ${peek?"fake":"authentic"}">`:""}<div class="auction-main"><div class="auction-top"><h3>${esc(a.item.name)}</h3><span class="tag">T${a.item.tier} ${esc(a.item.category)}</span></div>${tagList(a.item.tags)}${bidPanel(a,false)}</div></article>`;}
function bidPanel(a:PublicAuction,hero:boolean){const top=a.bids.at(-1),lead=top?.playerId===priv!.player.id,context=contextAbilities(a);return `<div class="bid-state"><div class="current-bid"><small>${lead?"YOU LEAD":"CURRENT BID"}</small><strong class="price" data-bid-value="${a.id}">${a.currentBid?fmt(a.currentBid):"No bids"}</strong><span class="min-bid">Minimum ${fmt(a.minBid)}</span></div>${countdown(a)}</div><div class="bid-controls"><input id="bid-${a.id}" type="number" min="${a.minBid}" value="${a.minBid}" aria-label="Bid amount for ${esc(a.item.name)}"><button class="primary" data-bid="${a.id}">Bid</button></div>${context?`<div class="ability-context">${context}</div>`:""}${hero?"":""}`;}
function countdown(a:PublicAuction){const duration=60000,remaining=Math.max(0,a.endsAt-Date.now()),pct=Math.min(1,remaining/duration),offset=113*(1-pct);return `<span class="countdown ${remaining<30000?"urgent":""}" data-end="${a.endsAt}"><svg viewBox="0 0 42 42" aria-hidden="true"><circle cx="21" cy="21" r="18"></circle><circle class="progress" cx="21" cy="21" r="18" stroke-dasharray="113" stroke-dashoffset="${offset}"></circle></svg><b class="timer">${shortTime(remaining)}</b></span>`;}
function contextAbilities(a:PublicAuction){const dep=currentDeployment();if(!dep||dep.redeployCooldownUntil>Date.now())return "";return Object.entries(priv!.player.abilities).flatMap(([id,slot])=>{const def=ability(id);if(!def||!["peek","reveal","shield","refund","tax","block"].includes(def.kind)||slot.readyAt>Date.now())return [];return [`<button data-context-ability="${id}" data-auction="${a.id}">${icon(`icons/${kindIcon(def.kind)}.svg`)}${esc(def.name)}</button>`];}).join("");}
function wireAuctions(){$('gameView').querySelectorAll<HTMLButtonElement>('[data-bid]').forEach(button=>button.onclick=()=>bid(button.dataset.bid!));$('gameView').querySelectorAll<HTMLButtonElement>('[data-context-ability]').forEach(button=>button.onclick=()=>openAbility(button.dataset.contextAbility!,button.dataset.auction));}
function bid(id:string){const input=$<HTMLInputElement>(`bid-${id}`),amount=Number(input.value);if(amount>priv!.player.coins*.3&&buttonConfirm(input)!==true)return;send({type:"BID",auctionId:id,amount});}
function buttonConfirm(input:HTMLInputElement){if(input.dataset.confirmed==="true"){delete input.dataset.confirmed;return true;}input.dataset.confirmed="true";toast("Large bid: press Bid again to confirm");setTimeout(()=>delete input.dataset.confirmed,4000);return false;}
function tagList(values:string[]){return `<div class="tags">${values.map(v=>`<span class="tag">${esc(v)}</span>`).join("")}</div>`;}

function renderOrders(){$('orders').innerHTML=state!.currentHouse!.orders.map(orderCard).join("");$('orders').querySelectorAll<HTMLButtonElement>('[data-order]').forEach(button=>button.onclick=()=>send({type:"FULFILL_ORDER",orderId:button.dataset.order,itemIds:[button.dataset.item]}));}
function orderMatch(o:Order){return priv!.items.find(i=>(!o.template.category||i.category===o.template.category)&&(!o.template.tag||i.tags.includes(o.template.tag))&&i.tier>=o.template.tierMin&&(o.template.fakeAllowed||!i.fake));}
function orderCard(o:Order){const match=orderMatch(o),label=o.template.category??`#${o.template.tag}`;return `<article class="order-card"><div class="requirement-row"><span class="tag">${esc(label)}</span><span class="tag">Tier ${o.template.tierMin}+</span><span class="tag">×${o.template.count}</span>${o.template.fakeAllowed?icon("icons/skull.svg","Fakes accepted"):""}</div><div class="reward-row"><span>${icon("icons/coin.svg","","coin-icon")}${fmt(o.reward.coins)}</span><span>${icon("icons/fame.svg","","fame-icon")}${fmt(o.reward.fame)}</span><span>${icon("icons/xp.svg","","xp-icon")}${fmt(o.reward.xp)}</span></div><button data-order="${o.id}" data-item="${match?.id??""}" ${match?"":"disabled"}>${match?`Fulfill with ${esc(match.name)}`:"No matching item"}</button></article>`;}
function renderLedger(){const h=state!.currentHouse!;$('ledger').innerHTML=`<section class="ledger"><p class="kicker">HOUSE LEDGER</p><div class="ledger-grid"><span>FEE<b>${Math.round(h.feeRate*100)}%</b></span><span>SPECIALTY<b>${esc(h.specialtyTag??"Open")}</b></span><span>HEAT<b>${Math.round(h.heat*100)}%</b></span><span>MEMBERS<b>${h.memberCount}</b></span></div>${heatMeter(h.heat)}<div class="section-title"><span>IN THE ROOM</span><i></i></div><div class="members">${h.members.map(m=>`<span class="member-chip"><img src="${asset(`characters/${m.characterId}.png`)}" alt="">${m.rookie?'<span title="Rookie">🌱</span> ':""}${esc(m.playerName)}</span>`).join("")}</div></section>`;}

function openAbility(id:string,presetAuction?:string){const def=ability(id);if(!def)return;const modal=$<HTMLDialogElement>('abilityModal');$('abilityModalTitle').textContent=def.name;$('abilityModalText').textContent=def.description;const needsAuction=["peek","reveal","shield","refund","tax","block"].includes(def.kind);if(!needsAuction){send({type:"USE_ABILITY",abilityId:id});return;}const auctions=state!.currentHouse!.auctions;if(presetAuction&&def.kind!=="block"){send({type:"USE_ABILITY",abilityId:id,auctionId:presetAuction});return;}$('abilityTargets').innerHTML=auctions.length?auctions.map(a=>`<button data-target-auction="${a.id}">${itemFrame(a.item)}<span><strong>${esc(a.item.name)}</strong><small class="muted"> ${shortTime(a.endsAt-Date.now())}</small></span></button>`).join(""):`<p class="empty">No valid targets.</p>`;$('abilityTargets').querySelectorAll<HTMLButtonElement>('[data-target-auction]').forEach(button=>button.onclick=e=>{e.preventDefault();const auction=auctions.find(a=>a.id===button.dataset.targetAuction)!;if(def.kind==="block")openPlayerTargets(id,auction);else{send({type:"USE_ABILITY",abilityId:id,auctionId:auction.id});modal.close();}});modal.showModal();}
function openPlayerTargets(id:string,auction:PublicAuction){const players=state!.currentHouse!.members.filter(m=>m.playerId!==priv!.player.id);$('abilityModalText').textContent=`Choose a rival to block on ${auction.item.name}.`;$('abilityTargets').innerHTML=players.map(p=>`<button data-target-player="${p.playerId}"><img src="${asset(`characters/${p.characterId}.png`)}" alt=""><strong>${esc(p.playerName)}</strong></button>`).join("");$('abilityTargets').querySelectorAll<HTMLButtonElement>('[data-target-player]').forEach(button=>button.onclick=e=>{e.preventDefault();send({type:"USE_ABILITY",abilityId:id,auctionId:auction.id,targetPlayerId:button.dataset.targetPlayer});$<HTMLDialogElement>('abilityModal').close();});}
function openItem(id:string){const item=priv!.items.find(i=>i.id===id);if(!item)return;const matches=state?.currentHouse?.orders.filter(o=>orderMatch(o)?.id===item.id)??[];$('itemActionContent').innerHTML=`<div class="item-detail">${itemFrame(item)}<div><p class="kicker">TIER ${item.tier} · ${esc(item.category)}</p><h2>${esc(item.name)}</h2>${tagList(item.tags)}${item.fake?`<p class="muted">Private note: unverified provenance.</p>`:""}</div></div><div class="item-actions"><label class="muted">Listing duration<select id="itemDuration"><option value="30">30 seconds</option><option value="60">1 minute</option></select></label><button class="primary" data-list-item="${item.id}">List in this house</button>${matches.map(o=>`<button data-fulfill-item="${item.id}" data-fulfill-order="${o.id}">Fulfill matching order</button>`).join("")}</div>`;const modal=$<HTMLDialogElement>('itemModal');$('itemActionContent').querySelector<HTMLButtonElement>('[data-list-item]')!.onclick=e=>{e.preventDefault();send({type:"LIST_ITEM",itemId:item.id,durationSec:Number($<HTMLSelectElement>('itemDuration').value)});modal.close();};$('itemActionContent').querySelectorAll<HTMLButtonElement>('[data-fulfill-order]').forEach(b=>b.onclick=e=>{e.preventDefault();send({type:"FULFILL_ORDER",orderId:b.dataset.fulfillOrder,itemIds:[b.dataset.fulfillItem]});modal.close();});modal.showModal();}
function showBoxReveal(item:Item){const overlay=$('boxReveal');$('revealItem').innerHTML=`<div class="t${item.tier}" style="--tier:var(--t${item.tier})">${itemFrame(item)}<h2>${item.tier===4?"LEGENDARY":`TIER ${item.tier}`}</h2><p>${esc(item.name)}</p></div>`;overlay.classList.remove("hidden");setTimeout(()=>overlay.classList.add("hidden"),4500);}
function showSeasonEnd(number:number){$('seasonEndTitle').textContent=`Season ${number} Complete`;$('seasonResultStats').innerHTML=priv?`<p><strong>${fmt(priv.player.fame)}</strong> final fame · <strong>${priv.player.fameMilestones.length}</strong> milestones</p>`:"";$('seasonOverlay').classList.remove("hidden");setTimeout(()=>$('seasonOverlay').classList.add("hidden"),5000);}
function showExtension(id:string){const card=document.querySelector<HTMLElement>(`[data-auction-card="${id}"]`);if(!card)return;const chip=document.createElement("span");chip.className="anti-snipe";chip.textContent="+5s";card.append(chip);setTimeout(()=>chip.remove(),900);}
function shortTime(ms:number){const seconds=Math.max(0,Math.ceil(ms/1000));if(seconds>=86400)return `${Math.floor(seconds/86400)}d ${Math.floor(seconds%86400/3600)}h`;if(seconds>=3600)return `${Math.floor(seconds/3600)}h ${Math.floor(seconds%3600/60)}m`;if(seconds>=60)return `${Math.floor(seconds/60)}m ${seconds%60}s`;return `${seconds}s`;}
function renderSeason(){if(!state)return;const left=Math.max(0,state.season.endsAt-Date.now()),el=$('season');el.textContent=`Season ${state.season.number} · ends in ${shortTime(left)}`;el.classList.toggle("warn",left<86400000);el.classList.toggle("danger",left<3600000);$('newSeasonCountdown').textContent=state.season.phase!=="active"?`Next season in ${shortTime(left)}`:"";}
function tick(){document.querySelectorAll<HTMLElement>('.countdown').forEach(el=>{const left=Math.max(0,Number(el.dataset.end)-Date.now()),circle=el.querySelector<SVGCircleElement>('.progress'),text=el.querySelector<HTMLElement>('.timer');if(circle)circle.style.strokeDashoffset=String(113*(1-Math.min(1,left/60000)));if(text)text.textContent=shortTime(left);el.classList.toggle("urgent",left<30000);});renderSeason();document.querySelectorAll<HTMLElement>('.deployment .cooldown').forEach(()=>{});}

$('accountForm').addEventListener("submit",async event=>{event.preventDefault();$('authError').textContent="";try{const response=await fetch(registerMode?"/api/register":"/api/login",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({username:$<HTMLInputElement>('username').value,password:$<HTMLInputElement>('password').value})}),body=await response.json() as {token?:string;error?:string};if(!response.ok||!body.token)throw new Error(body.error??"Authentication failed");localStorage.setItem("bidHouseToken",body.token);authenticating=true;send({type:"AUTH",token:body.token});}catch(error){const text=error instanceof Error?error.message:"Authentication failed";$('authError').textContent=text;toast(text,"error");}});
$('accountToggle').onclick=()=>{registerMode=!registerMode;$('accountTitle').textContent=registerMode?"Request membership":"Welcome back";$('accountSubmit').textContent=registerMode?"Create account":"Enter the house";$('accountToggle').textContent=registerMode?"Already a member? Log in":"New bidder? Request membership";$<HTMLInputElement>('password').autocomplete=registerMode?"new-password":"current-password";};
$('characterPrev').onclick=()=>{selectedCharacter--;renderCharacters(true);};$('characterNext').onclick=()=>{selectedCharacter++;renderCharacters(true);};$('confirmCharacter').onclick=()=>{const chosen=characters[selectedCharacter];if(!chosen)return;if(!pendingHouse){pendingCharacterId=chosen.id;renderHouses();show("house");toast(`Choose a house for ${chosen.name}`);return;}send({type:"DEPLOY",houseId:pendingHouse,characterId:chosen.id});pendingHouse=undefined;pendingCharacterId=undefined;};
$<HTMLSelectElement>('houseSwitcher').onchange=event=>{const value=(event.currentTarget as HTMLSelectElement).value;if(value)send({type:"ENTER_HOUSE",houseId:value});else show("house");};$('brandHome').onclick=()=>show("house");$('logout').onclick=()=>{localStorage.removeItem("bidHouseToken");location.reload();};$('openBox').onclick=()=>send({type:"OPEN_BOX"});$('skipReveal').onclick=()=>$('boxReveal').classList.add("hidden");
$('mobileNav').querySelectorAll<HTMLButtonElement>('[data-panel]').forEach(button=>button.onclick=()=>{const panel=button.dataset.panel;$('mobileNav').querySelectorAll('button').forEach(b=>b.classList.toggle("active",b===button));document.querySelectorAll<HTMLElement>('[data-mobile-panel]').forEach(el=>el.classList.toggle("active-mobile",el.dataset.mobilePanel===panel));});
setInterval(tick,1000);connect();
