import type { AbilityDefinition,Character,HouseSummary,PrivateState,PublicAuction,PublicState,ServerMessage } from "../shared/types.js";
const $=<T extends HTMLElement>(id:string)=>document.getElementById(id) as T;let socket:WebSocket,state:PublicState|undefined,priv:PrivateState|undefined,characters:Character[]=[],registerMode=false,authenticating=false,pendingHouse:string|undefined,inGame=false;
const esc=(s:string)=>s.replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[c]!)),send=(m:object)=>socket?.readyState===WebSocket.OPEN&&socket.send(JSON.stringify(m));
function toast(message:string,error=false){const e=document.createElement("div");e.className=`toast${error?" error":""}`;e.textContent=message;$("toasts").append(e);setTimeout(()=>e.remove(),3500);}
function show(view:"account"|"house"|"game"){for(const id of ["accountView","houseView","gameView"])$(id).classList.toggle("hidden",id!==`${view}View`);}
function connect(){socket=new WebSocket(`${location.protocol==="https:"?"wss":"ws"}://${location.host}`);socket.onopen=()=>{$("connection").textContent="Connected";const token=localStorage.getItem("bidHouseToken");if(token){authenticating=true;send({type:"AUTH",token});}else show("account");};socket.onclose=()=>{$("connection").textContent="Reconnecting...";setTimeout(connect,1000);};socket.onmessage=e=>handle(JSON.parse(String(e.data)) as ServerMessage);}
function handle(m:ServerMessage){if(m.type==="AUTH_OK"){authenticating=false;if(m.needsCharacter)show("house");}else if(m.type==="HOUSE_LIST"){if(state)state.houses=m.houses;renderHouses();}else if(m.type==="WELCOME"){priv=m.privateState;inGame=true;show("game");render();}else if(m.type==="STATE"){state=m.publicState;characters=state.characters;populateCharacters();renderHouses();render();renderSeason();}else if(m.type==="PRIVATE"){priv=m.privateState;if(m.message)toast(m.message);renderHouses();render();}else if(m.type==="FEATURED")toast("A featured auction has been selected");else if(m.type==="ERROR"){if(authenticating){localStorage.removeItem("bidHouseToken");show("account");}toast(m.message,true);}else if(m.type==="ANNOUNCEMENT")toast(m.message);else if(m.type==="SEASON_END")toast(`Welcome to Season ${m.number}!`);}
function populateCharacters(){const sel=$("character") as HTMLSelectElement;if(sel.options.length||!characters.length)return;characters.forEach(c=>sel.add(new Option(c.name,c.id)));showCharacter();}
function showCharacter(){const c=characters.find(x=>x.id===($("character") as HTMLSelectElement).value);$("characterDetail").textContent=c?`${c.passive} Abilities: ${[c.mainAbility,...c.traits].join(", ")}`:"";}
function renderHouses(){if(!state)return;const mine=priv?.deployments??[];$("deployments").innerHTML=mine.length?`<strong>Your deployments</strong>${mine.map(d=>`<div class="deployment"><span class="tag">${esc(characters.find(c=>c.id===d.characterId)?.name??d.characterId)} @ ${esc(state!.houses.find(h=>h.id===d.houseId)?.name??"house")}${d.redeployCooldownUntil>Date.now()?` | cooldown ${Math.ceil((d.redeployCooldownUntil-Date.now())/3600000)}h`:""}</span><select data-redeploy="${d.characterId}"><option value="">Move to...</option>${state!.houses.filter(h=>h.id!==d.houseId).map(h=>`<option value="${h.id}">${esc(h.name)}</option>`).join("")}</select></div>`).join("")}`:"<p class='muted'>No deployments yet.</p>";$("deployments").querySelectorAll<HTMLSelectElement>("[data-redeploy]").forEach(s=>s.onchange=()=>s.value&&send({type:"REDEPLOY",characterId:s.dataset.redeploy,toHouseId:s.value}));$("houses").innerHTML=state.houses.map(h=>houseCard(h,mine.some(d=>d.houseId===h.id))).join("");$("houses").querySelectorAll<HTMLButtonElement>("[data-enter]").forEach(b=>b.onclick=()=>send({type:"ENTER_HOUSE",houseId:b.dataset.enter}));$("houses").querySelectorAll<HTMLButtonElement>("[data-deploy]").forEach(b=>b.onclick=()=>{pendingHouse=b.dataset.deploy;($("characterDialog") as HTMLDialogElement).showModal();});}
function houseCard(h:HouseSummary,active:boolean){const deployed=priv?.deployments.some(d=>d.houseId===h.id)||state?.currentHouse?.id===h.id;return `<article class="card house-card"><div class="row"><h3>${esc(h.name)}</h3><span>${h.specialtyTag?"#"+esc(h.specialtyTag):"All goods"}</span></div><p class="muted">${Math.round(h.feeRate*100)}% fee | Prime ${String(h.primeHour).padStart(2,"0")}:00 UTC | ${h.memberCount} members</p><div class="heat"><i style="width:${Math.min(100,h.heat*100)}%"></i></div><p class="muted">${h.liveAuctions} auctions | ${h.liveOrders} orders | Heat ${h.heat.toFixed(1)}</p>${deployed||active?`<button data-enter="${h.id}">Enter</button>`:(priv?.deployments.length??0)<3?`<button data-deploy="${h.id}">Deploy</button>`:""} </article>`;}
function tags(xs:string[]){return `<div class="tags">${xs.map(t=>`<span class="tag">${esc(t)}</span>`).join("")}</div>`;}
function render(){if(!state||!priv||!state.currentHouse)return;const h=state.currentHouse,dep=priv.deployments.find(d=>h.members.some(m=>m.playerId===priv!.player.id&&m.characterId===d.characterId))!,c=characters.find(x=>x.id===dep.characterId)!;$("houseTitle").textContent=h.name;$("houseFee").textContent=`${Math.round(h.feeRate*100)}% house fee`;$("wallet").textContent=`${priv.player.coins} coins | ${priv.player.xp} XP | ${priv.player.fame} fame`;$("identity").innerHTML=`<strong>${esc(c.name)}</strong><br><span class="muted">${esc(c.passive)} | ${priv.player.boxes} free boxes${dep.redeployCooldownUntil>Date.now()?" | REDEPLOY COOLDOWN":""}</span>`;
 $("inventory").innerHTML=priv.items.length?priv.items.map(i=>`<article class="card"><div class="row"><strong>${esc(i.name)}</strong><span>T${i.tier}</span></div><p class="muted">${i.category} | ${i.fake?"FAKE":"AUTHENTIC"}</p>${tags(i.tags)}<div class="bidline"><select id="dur-${i.id}"><option value="30">30 sec</option><option value="60">1 min</option></select><button data-list="${i.id}">List</button></div></article>`).join(""):"<p class='muted'>Open a box or win an auction.</p>";$("inventory").querySelectorAll<HTMLButtonElement>("[data-list]").forEach(b=>b.onclick=()=>send({type:"LIST_ITEM",itemId:b.dataset.list,durationSec:Number(($("dur-"+b.dataset.list) as HTMLSelectElement).value)}));
 const ids=[c.mainAbility,...c.traits];$("abilities").innerHTML=ids.map(id=>{const d=state!.abilities.find(a=>a.id===id)!,ready=Math.max(0,(priv!.player.abilities[id]?.readyAt??0)-Date.now()),blocked=dep.redeployCooldownUntil>Date.now();return `<button data-ability="${id}" title="${esc(d.description)}" ${ready>0||blocked?"disabled":""}>${esc(d.name)}${ready>0?` ${Math.ceil(ready/1000)}s`:""}</button>`;}).join("");$("abilities").querySelectorAll<HTMLButtonElement>("button").forEach(b=>b.onclick=()=>useAbility(b.dataset.ability!));
 $("auctions").innerHTML=h.auctions.length?h.auctions.map(auctionCard).join(""):"<p class='muted'>No live lots.</p>";$("auctions").querySelectorAll<HTMLButtonElement>("[data-bid]").forEach(b=>b.onclick=()=>send({type:"BID",auctionId:b.dataset.bid,amount:Number(($("bid-"+b.dataset.bid) as HTMLInputElement).value)}));
 $("orders").innerHTML=h.orders.map(o=>{const match=priv!.items.find(i=>(!o.template.category||i.category===o.template.category)&&(!o.template.tag||i.tags.includes(o.template.tag))&&i.tier>=o.template.tierMin&&(o.template.fakeAllowed||!i.fake));return `<article class="card"><strong>${esc(o.template.category??"#"+o.template.tag)} | Tier ${o.template.tierMin}+</strong><p class="muted">${o.reward.coins} coins / ${o.reward.fame} fame</p><button data-order="${o.id}" data-item="${match?.id??""}" ${match?"":"disabled"}>${match?"Fulfill":"No match"}</button></article>`;}).join("");$("orders").querySelectorAll<HTMLButtonElement>("[data-order]").forEach(b=>b.onclick=()=>send({type:"FULFILL_ORDER",orderId:b.dataset.order,itemIds:[b.dataset.item]}));}
function auctionCard(a:PublicAuction){const peek=priv?.peeked[a.item.id],top=a.bids.at(-1);return `<article class="card ${a.featured?"featured":""}">${a.featured?'<span class="feature-badge">FEATURED</span>':""}<div class="row"><strong>${esc(a.item.name)}</strong><span>T${a.item.tier}</span></div>${tags(a.item.tags)}<p class="muted">${a.item.category} | Seller hidden | ${peek===undefined?"Authenticity unknown":peek?"FAKE":"AUTHENTIC"}</p><div class="row"><span>${a.currentBid||"No bids"}${top?.playerId===priv?.player.id?" | You lead":""}</span><strong class="timer" data-end="${a.endsAt}"></strong></div><div class="bidline"><input id="bid-${a.id}" type="number" min="${a.minBid}" value="${a.minBid}"><button data-bid="${a.id}">Bid</button></div></article>`;}
function useAbility(id:string){const d=state!.abilities.find(x=>x.id===id) as AbilityDefinition,a=state!.currentHouse!.auctions[0];if(["peek","reveal","shield","refund","tax","block"].includes(d.kind)){if(!a)return toast("No live auction to target",true);send({type:"USE_ABILITY",abilityId:id,auctionId:a.id,targetPlayerId:a.bids.find(b=>b.playerId!==priv!.player.id)?.playerId});}else send({type:"USE_ABILITY",abilityId:id});}
function renderSeason(){if(!state)return;const ms=Math.max(0,state.season.endsAt-Date.now());$("season").textContent=`Season ${state.season.number} | ${Math.floor(ms/86400000)}d ${Math.floor(ms%86400000/3600000)}h ${Math.floor(ms%3600000/60000)}m`;}
$("accountForm").addEventListener("submit",async e=>{e.preventDefault();try{const r=await fetch(registerMode?"/api/register":"/api/login",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({username:($("username") as HTMLInputElement).value,password:($("password") as HTMLInputElement).value})}),d=await r.json() as {token?:string;error?:string};if(!r.ok||!d.token)throw new Error(d.error??"Authentication failed");localStorage.setItem("bidHouseToken",d.token);authenticating=true;send({type:"AUTH",token:d.token});}catch(e){toast(e instanceof Error?e.message:"Authentication failed",true);}});
$("accountToggle").onclick=()=>{registerMode=!registerMode;$("accountTitle").textContent=registerMode?"Register":"Log in";$("accountSubmit").textContent=registerMode?"Register":"Log in";};$("character").addEventListener("change",showCharacter);$("confirmDeploy").onclick=e=>{e.preventDefault();if(pendingHouse)send({type:"DEPLOY",houseId:pendingHouse,characterId:($("character") as HTMLSelectElement).value});($("characterDialog") as HTMLDialogElement).close();};$("browse").onclick=()=>show("house");$("closeBrowser").onclick=()=>inGame&&show("game");$("openBox").onclick=()=>send({type:"OPEN_BOX"});setInterval(()=>{document.querySelectorAll<HTMLElement>(".timer").forEach(e=>e.textContent=`${Math.max(0,Math.ceil((Number(e.dataset.end)-Date.now())/1000))}s`);renderSeason();renderHouses();},1000);connect();
